### PR TITLE
No need to require bash to run tests

### PR DESCRIPTION
**Pull request by melted**
I had to install bash on my FreeBSD server to run the tests, and that felt unnecessary, it's not like it's actually using any bash feature.

### CODE REVIEW

**Comment by Melvar** [comment]
Are you sure? Did you check every test? I thought there was at least one using arrays.

**Comment by melted** [comment]
We'll see, Travis uses dash for sh, I'm pretty sure that sh is bash locally for me.

**Comment by melted** [comment]
Looking good.

**Comment by Melvar** [comment]
Yep, `primitives002` does use arrays, because it was by far the easiest way for me to fix it. `reg039` and `basic010` also do to attempt shellescaping with their timeout thing.

**Comment by melted** [comment]
well, then I put this on ice

**Pull request closed without merging**
