### PR TITLE
Use system to allow $EDITOR with args

### LINKED ISSUE #2963: EDITOR should support commands with spaces
It's nice to be able to use EDITOR to set command line arguments to the editor. Presently:
```
enolan at Behemoth in ~/mystuff/code/Idris-dev-tests [parse*] 
$ EDITOR="emacs -nw" stack exec -- idris foo.idr
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 0.10-git:fa9af46
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Type checking ./foo.idr
*foo> :e
Uncaught error: emacs -nw: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)
```

### PR DESCRIPTION
**Pull request by melted**
Fixes #2963

### CODE REVIEW

**Comment by jfdm** [comment]
Can the changelog be updated please to reflect the new functionality.

Possibly as an extra, provision of general advice on how to use.

**Comment by melted** [comment]
Ah, yes, it's a feature not a bug.

**Comment by Melvar** [comment]
Does this work if the file path has for example `$` in it?

**Comment by melted** [comment]
It should use `'` as quote on unixen and `"` on windows (because system runs cmd, and cmd only uses double quotes)

**Comment by ahmadsalim** [comment]
@melted Any reason why this has not been merged yet? :)

**Comment by ericqweinstein** [comment]
LGTM after conflicts resolved 👍

**Comment by Melvar** [comment]
To me it doesn’t look as though the necessary escaping has been added yet.

**Comment by melted** [comment]
Ah yes, I finished this long ago.

**Pull request merged**
