### PR TITLE
tutorial: replace "return" with "pure"

### LINKED ISSUE #3453: "return" still present in tutorial
https://github.com/idris-lang/Idris-dev/search?utf8=%E2%9C%93&q=m_add+x+y+%3D+return+%28%21x+%2B+%21y%29&type=Code

### PR DESCRIPTION
**Pull request by siddharthist**
Tested and working :smile: 

fixes #3453 
```
*classes> :t m_add
m_add : Maybe Int ->
        Maybe Int -> Maybe Int
*classes> m_add (Just 5) (Just 6)
Just 11 : Maybe Int
*classes> :quit
Bye bye
```

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@siddharthist Could you kindly also update the documentation in this PR?

**Comment by siddharthist** [comment]
@ahmadsalim Which file did you have in mind?

**Comment by ahmadsalim** [comment]
The one you linked in your issue #3453.

**Comment by ahmadsalim** [comment]
`docs/tutorial/interfaces.rst `

**Comment by siddharthist** [comment]
@ahmadsalim done!

**Comment by jfdm** [comment]
I fixed up some other places outside the tutorial (and within) in which `return` was being used. Thanks for the contribution.

**Pull request merged**
