### PR TITLE
Added *.dSYM to .gitignore since it is generated by a test on mac

### PR DESCRIPTION
**Pull request by ahmadsalim**

### CODE REVIEW

**Comment by jfdm** [comment]
Before you get too worried @ahmadsalim if you look at the log files, the reason the build failed is not your fault.

**Comment by ahmadsalim** [comment]
@jfdm Thanks! I was totally wondering why it would fail on such simple thing :).

**Comment by jfdm** [comment]
No worries.

**Comment by jfdm** [comment]
Oh @ahmadsalim the upstream problem has been fixed. TBH I do not know the right protocol here, that is whether to merge, or ask you to rebase and rerun the tests just so we know the tests will pass. This is because you PR is not dependent on the upstream fix (i.e. there are no consistency issues) so, I leave it up to you.

**Comment by ahmadsalim** [comment]
@jfdm I can rebase on upstream when I get home :).

**Pull request merged**
