### PR TITLE
random numbers for ST

### PR DESCRIPTION
**Pull request by rbarreiro**
adaptation of effects Random to Control.ST, it works like
```
  rnd <- new 1
  x1 <- getRandom rnd
  x2 <- getRandom rnd
  delete rnd
```

### CODE REVIEW

**Comment by gergoerdi** [comment]
Nice, this is just what I (would have) needed for https://github.com/gergoerdi/icfp-bingo-2017-idris, instead of lifting the `effects` version into ST!

**Comment by clayrat** [comment]
Ha, I also had a go at it here: https://github.com/clayrat/st-random/blob/master/src/Control/ST/Random.idr, using `Bits` and a xorshift+ generator. The stumbling point for me personally, however, was generating a sequence of random numbers - I couldn't figure out how to write something like `traverse` or `foldM` for `Control.ST`.

**Comment by ahmadsalim** [comment]
@rbarreiro Thanks!

**Comment by clayrat** [comment]
Now that https://github.com/idris-lang/Idris-dev/pull/4185 is merged we could try having another go at `traverse`...

**Comment by rbarreiro** [comment]
I handled it like this:
```idris
interface (Functor t, Foldable t) => TraversableST (t : Type -> Type) where
  traverseST : (a -> STrans m b r (const r)) -> t a -> STrans m (t b) r (const r)

implementation TraversableST List where
  traverseST f [] = pure []
  traverseST f (x::xs) =
    do
      z <- f x
      zs <- traverseST f xs
      pure (z::zs)

sequenceST : TraversableST t => t (STrans m a r (const r)) -> STrans m (t a) r (const r)
sequenceST = traverseST id
```

**Pull request merged**
