### PR TITLE
A test for lines/unlines.

### PR DESCRIPTION
**Pull request by steshaw**
A test for the current behaviour of `lines` and `unlines` which I believe to be incorrect (or at least misleading). I've raised an issue about this: #3278.

Note that this can be merged as-is as it tests the current behaviour of `lines` and `unlines`. However, I'm happy to work it into a fix for the issue.

### CODE REVIEW

**Comment by jfdm** [comment]
@steshaw Thanks for the PR. 

Travis is failing due to an issue not related to your PR, so please do not worry about Travis not completing. This is happening across a few other PRs.

Once your other issue (#3278) has been resolved, and travis failing, we can look at getting this merged.

**Comment by jfdm** [comment]
@steshaw Just to let you know that Idris' test suite has been revamped to work using `tasty`. I am wondering if it is possible for you to rebase this PR off of master, just so we know there aren't any undue side-effects before we merge.

**Comment by steshaw** [comment]
@jfdm rebased off master and updated to `tasty`. Looks ready to merge.

**Comment by jfdm** [comment]
Thanks, everything looks ok.

**Pull request merged**
