### PR TITLE
Just/Nothing for intro was split into intro/intro'

### PR DESCRIPTION
**Pull request by bitemyapp**
Fixing Elab docs.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Thanks so much!

**Comment by bitemyapp** [comment]
@david-christiansen is it safe to say the best way to see more worked up examples of Elab are the repos on your Github account? Best I've found so far.

**Comment by david-christiansen** [comment]
Yes, for now. Unfortunately. There's also a few in the test suite, under test/metaNNN in the source repo.

**Comment by bitemyapp** [comment]
@david-christiansen ah! That's really helpful, thank you!

**Pull request merged**
