### PR TITLE
Update ffi.rst to show example of correct including C code and exampl…

### PR DESCRIPTION
**Pull request by bigos**
…e Makefile

That would save a lot of time since simple examples are hard to find.

### CODE REVIEW

**Comment by unalos** [comment]
Ideally, I'd rather have documentation on how to use idris --build rather than a Makefile. As you do not really need a Makefile for this.

**Comment by unalos** [comment]
I also took time to figure it out. This part of the documentation needs improvement IMHO.

The problem I see is that using a Makefile in this way ultimately is misleading, as it encourages not to use the .ipkg files which provide a standard way to bundle the code in packages and install them locally with idris --install. For instance https://github.com/unalos/idris-mongo/blob/master/Makefile

(I won't be the one deciding to accept or reject your PR. I just wanted to provide my take on it.)

**Comment by bigos** [comment]
I did not read about .ipkg files yet. I think creating a simple minimalistic project to illustrate the point and linking to it from the tutorial would be a better idea.

**Comment by melted** [comment]
It would be valuable to have an ipkg example too, and how to it just from the command line too. Still, some documentation is better than no documentation. We can expand it in further PRs.

Thanks!

**Pull request merged**
