### PR TITLE
Building with stack works on OSX El Capitan + gmp/libffi

### PR DESCRIPTION
**Pull request by ydewit**
These are the steps:
```
brew install libffi
brew install gmp

PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig stack build
```

### CODE REVIEW

**Comment by jfdm** [comment]
A concern with this approach is that we are hard coding the extra directories in the `stack.yaml` specifically for Mac OS X users who use HomeBrew.

**Comment by ydewit** [comment]
@jfdm Yes, indeed. I am not sure there is a way to conditionally include includes and libs in Stack. Maybe the simplest for now is to choose one way of getting the dependencies in OSX (for instance, using brew) and then have a OSX specific stack-osx.yaml. And another one for linux, e.g stack-linux.yaml etc.

**Comment by zjhmale** [comment]
@ydewlt @jfdm how about use command params `--extra-include-dirs` and `--extra-lib-dirs` instead of hard coding the extra directories?

**Comment by rodlogic** [comment]
@zjhmale I guess my motivation for making this change in the first place was to reduce the barriers to build idris. Having to add extra arguments every time we need to build Idris doesn't strike me a ideal. Although, I do see the point of hard coding the extra directories.

Shouldn't we just come up with 'the' Idris way of building on each OS and then make sure it is as simple as ```stack build``` after the requirements are installed? E.g. in the case of OSX, it could mean documenting a one time setup:
1. Install brew
2. Install libffi (```brew install ffi```)
3. Install gmp (```brew install gmp```)
4. Add ```export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig``` to ```.bashrc```
5. Clone the Idris-dev repo

Then just rely on ```stack``` to build Idris.

Each OS would have it's own recommended way of build Idris.

**Comment by zjhmale** [comment]
@rodlogic ok

**Comment by jfdm** [comment]
@ydewit thanks for the contribution however, I do not think it should be merged. The bump of Stack versions should be, but done in a secondary PR subject to tests passing.

My reasoning for not merging is this: 

> Not everyone who develops Idris on Mac OS X uses HomeBrew, and not all of those that develop on Idris use stack. By assuming when using stack where libraries are located is too restrictive on the configuration. It would be better for the flexibility to remain. Moreover, keeping separate stack configurations for different platform is too much effort. Also specialising cabal to cater for a single developer audience is also complicating the build unnecessarily.

I think the guidance in INSTALL.md should be updated to reflect how stack can be run with extra paths, negating the advice of prepending and amending an environment variable.

For advice on how to build Idris-Dev for a specific platform, please see the [wiki pages](https://github.com/idris-lang/Idris-dev/wiki/Installation-Instructions). This advice should be updated as well.

Finally, there is already an (unofficial) formula for Idris in Homebrew that takes into account building with FFI and GMP and uses the correct paths.

**Pull request closed without merging**
