### PR TITLE
Delete obsolete tailcall test

### PR DESCRIPTION
**Pull request by melted**
Also update the comment.

### CODE REVIEW

**Comment by edwinb** [comment]
To be honest, I think we should remove this test rather than make it more lenient... it's not actually testing anything that isn't covered elsewhere.

**Comment by melted** [comment]
Ok, I'll remove it

**Comment by melted** [comment]
Timeout in travis, seven of eight is enough...

**Comment by jfdm** [comment]
In future, if Travis has timed out can you restart the affected build rather than merge the PR; a commit bit allows you to do that on Travis if you log in. Given that the timeout was on the C backend it would be better if the PRs built cleanly prior to a merge.

**Pull request merged**
