### PR TITLE
Merging the `codata` documentation into master

### PR DESCRIPTION
**Pull request by ahmadsalim**
We had merged #2988 into a separate `documentation/codata` page since there were some discussion on improvements/further collaboration, but there has been no changes added since then. I think therefore it is better to merge it into master, to provide some documentation now which can then be improved later as per @jfdm's suggestions.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
Thanks @lambda-11235 for adding the documentation!

**Comment by ahmadsalim** [comment]
You are welcome to add yourself to the `CONTRIBUTORS` file if you so wish.

**Comment by lambda-11235** [comment]
It's been a while, but may I still add myself to CONTRIBUTORS?

**Comment by david-christiansen** [comment]
Contributors get to be in `CONTRIBUTORS` even if it's been a while :-)

**Comment by lambda-11235** [comment]
Should I just make a pull request?

**Comment by david-christiansen** [comment]
Yep!

**Pull request merged**
