### PR TITLE
Algebra proofs

### PR DESCRIPTION
**Pull request by Sventimir**
The module `Control.Algebra.Laws` introduces proofs of some basic basic laws of algebra, such as that anything multiplied by zero is zero or inverse composed with inverse is identity. These proofs might be helpful in proving more complex facts about algebraic structures.

I'm not sure if the coding style complies well with the rest of the package. If it doesn't or there are some similarly basic proofs that I overlooked, I'll be happy to fix it.

### CODE REVIEW

**Comment by clayrat** [comment]
You can put multiple bindings under one `let` block, i.e.
```
let
  foo = 1
  bar = "a"
  ...
 in
...
```

**Comment by Sventimir** [comment]
Sure, why not.

**Comment by melted** [comment]
Thanks!

**Comment by Sventimir** [comment]
Your welcome :)

**Pull request merged**
