### PR TITLE
Relax safe bounds, Fixes #3543.

### LINKED ISSUE #3543: safe == 0.3.9
I didn't understand change aa91025 well.

Would `safe >= 0.3.9` not work equally well?

It looks like if this was done then latest idris might build in Stackage Nightly again.

### PR DESCRIPTION
**Pull request by jfdm**
Adjusted bounds in cabal file, but not in stack config. That can come later.

### CODE REVIEW

**Comment by jfdm** [comment]
Right, after digging around I *think* we are experiencing [this cabal issue](https://github.com/haskell/cabal/issues/3003). Whilst a backdated patch was released for 'older' cabal versions, it appears that the [HVR PPA](https://launchpad.net/~hvr/+archive/ubuntu/ghc) to get ghc versions on Ubuntu didn't push the fixed version of Cabal for 1.20. This is the cabal we are experiencing problems with.

Two ways, forward: 

1. We bump the cabal versions to latest and greatest for all build's. IIRC cabal is backwards compatible. This comes at the cost of realistic assumptions about ghc and cabal version parings, however, we could assume and specify that everyone where they can updates their cabal, and ensure that PATH is setup correctly.

2. We ask HVR to provide a more up-to-date version of Cabal in their archive.

**Comment by juhp** [comment]
I am not sure, but would:

```
if impl(ghc < 7.7)
   Build-depends: safe == 0.3.9
```

help?

**Comment by jfdm** [comment]
@juhp I've done (2), and didn't think of adding in a conditional to cabal. Although, I am not in favour of such conditionals, I do see their need. I've pushed a fix and hopefully this will work. Thanks for the comments.

**Comment by jfdm** [comment]
The Mac OS X build timed out during benchmarking. Given that the rest of the test suite passed, and the change resulted in a successful build and test run, I think it is safe to merge.

**Comment by juhp** [comment]
Thanks!  Then hopefully the next release will build in Stackage Nightly again. :-)

Only other suggest that came to mind now was requiring newer Cabal to build, but your change looks good/optimal to me.

**Pull request merged**
