### PR TITLE
expand Bool laws, add (verified) lattice instances for Bool & Nat

### PR DESCRIPTION
**Pull request by clayrat**

### CODE REVIEW

**Comment by clayrat** [comment]
Looks like there's some kind of stack issue, only for GHC 8.4.1

**Comment by melted** [comment]
Yes, there is something unrelated with the stack build.

But reg024 fails on Appveyor, I'll restart it to see if it was intermittent.

**Comment by clayrat** [comment]
Now `st002` fails, seems random

**Comment by melted** [comment]
Let's merge. CI failures are unrelated.

**Pull request merged**
