### PR TITLE
Various additions to contrib

### PR DESCRIPTION
**Pull request by Synthetica9**
* `Data.SortedBag`: Bag (or Multiset) implemention based on `Data.SortedMap`.
  * `Data.PosNat`: A `Nat` paired with a proof that it is positive.
  * `Data.Chain`: A function with an arbitrary number of arguments, plus combinators for working with them.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
Thanks!

**Comment by Melvar** [comment]
`Data.Chain.Chain` appears to be a special case of `Data.Fun.Fun`. Why was this added as a separate module?

**Comment by Synthetica9** [comment]
@Melvar The case where all arguments are of the same type allows for more combinators to be defined, see for example `reflexes` and `before`.

**Comment by Melvar** [comment]
Sure, but there is a duplicate, and they’re closely related … a separate module seems overkill. Also I’m suspicious about the usefulness – remember that Idris can’t invert `Chain`, so a lot of specifying implicits is likely to be required. (The same with `Fun`.)

**Pull request merged**
