### PR TITLE
Boolean monoid wrappers

### PR DESCRIPTION
**Pull request by jachymb**

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@jachymb Thanks for the PR. Could you however kindly put it in `contrib` rather than `prelude`?

**Comment by jachymb** [comment]
I am not sure what would be the suitable place in the codebase where it should be put then. Any recommendations please?

**Comment by ahmadsalim** [comment]
Make a folder called Bool in `https://github.com/idris-lang/Idris-dev/tree/master/libs/contrib/Data` and then add your changes under a file of suitable name.

**Comment by jachymb** [comment]
This would be probably better in #3557

**Comment by ahmadsalim** [comment]
If you think it's better to consider this under #3557 I will close the PR.
Please reopen it if you would like it under separate consideration again.

**Pull request closed without merging**
