### PR TITLE
Support cabal 3.4 (latest)

### PR DESCRIPTION
**Pull request by ice1000**
Let's be kind to cabal users :-)

### CODE REVIEW

**Comment by melted** [comment]
Thanks!

**Comment by fedeinthemix** [comment]
It fails for me with cabal 3.4 and GHC 8.10.4. Here's the log.

```
$ cabal install idris --program-prefix=/opt/idris/idris-1
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: idris-1.3.3 (user goal)
[__1] next goal: idris:setup.Cabal (dependency of idris)
[__1] rejecting: idris:setup.Cabal-3.2.1.0/installed-3.2.1.0 (conflict: idris
=> idris:setup.Cabal>=2.4 && <3.1)
[__1] skipping: idris:setup.Cabal-3.4.0.0, idris:setup.Cabal-3.2.1.0,
idris:setup.Cabal-3.2.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=2.4 && <3.1' from 'idris')
[__1] rejecting: idris:setup.Cabal-3.0.2.0, idris:setup.Cabal-3.0.1.0,
idris:setup.Cabal-3.0.0.0, idris:setup.Cabal-2.4.1.0,
idris:setup.Cabal-2.4.0.1, idris:setup.Cabal-2.4.0.0,
idris:setup.Cabal-2.2.0.1, idris:setup.Cabal-2.2.0.0,
idris:setup.Cabal-2.0.1.1, idris:setup.Cabal-2.0.1.0,
idris:setup.Cabal-2.0.0.2, idris:setup.Cabal-1.24.2.0,
idris:setup.Cabal-1.24.0.0, idris:setup.Cabal-1.22.8.0,
idris:setup.Cabal-1.22.7.0, idris:setup.Cabal-1.22.6.0,
idris:setup.Cabal-1.22.5.0, idris:setup.Cabal-1.22.4.0,
idris:setup.Cabal-1.22.3.0, idris:setup.Cabal-1.22.2.0,
idris:setup.Cabal-1.22.1.1, idris:setup.Cabal-1.22.1.0,
idris:setup.Cabal-1.22.0.0, idris:setup.Cabal-1.20.0.4,
idris:setup.Cabal-1.20.0.3, idris:setup.Cabal-1.20.0.2,
idris:setup.Cabal-1.20.0.1, idris:setup.Cabal-1.20.0.0,
idris:setup.Cabal-1.18.1.7, idris:setup.Cabal-1.18.1.6,
idris:setup.Cabal-1.18.1.5, idris:setup.Cabal-1.18.1.4,
idris:setup.Cabal-1.18.1.3, idris:setup.Cabal-1.18.1.2,
idris:setup.Cabal-1.18.1.1, idris:setup.Cabal-1.18.1,
idris:setup.Cabal-1.18.0, idris:setup.Cabal-1.16.0.3,
idris:setup.Cabal-1.16.0.2, idris:setup.Cabal-1.16.0.1,
idris:setup.Cabal-1.16.0, idris:setup.Cabal-1.14.0, idris:setup.Cabal-1.12.0,
idris:setup.Cabal-1.10.2.0, idris:setup.Cabal-1.10.1.0,
idris:setup.Cabal-1.10.0.0, idris:setup.Cabal-1.8.0.6,
idris:setup.Cabal-1.8.0.4, idris:setup.Cabal-1.8.0.2,
idris:setup.Cabal-1.6.0.3, idris:setup.Cabal-1.6.0.2,
idris:setup.Cabal-1.6.0.1, idris:setup.Cabal-1.4.0.2,
idris:setup.Cabal-1.4.0.1, idris:setup.Cabal-1.4.0.0,
idris:setup.Cabal-1.2.4.0, idris:setup.Cabal-1.2.3.0,
idris:setup.Cabal-1.2.2.0, idris:setup.Cabal-1.2.1, idris:setup.Cabal-1.1.6,
idris:setup.Cabal-1.24.1.0 (constraint from minimum version of Cabal used by
Setup.hs requires >=3.2)
[__1] fail (backjumping, conflict set: idris, idris:setup.Cabal)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: idris, base, hashable, text,
blaze-builder, blaze-markup, trifecta, haskeline, idris:setup.Cabal,
optparse-applicative, unordered-containers, ivor
Try running with --minimize-conflict-set to improve the error message.

```

**Comment by ice1000** [comment]
> [__1] rejecting: idris:setup.Cabal-3.2.1.0/installed-3.2.1.0 (conflict: idris
=> idris:setup.Cabal>=2.4 && <3.1)

Seems your idris source is not new somehow. Maybe you need to update something, but I'm not sure.

**Comment by gallais** [comment]
> cabal install idris 

The last upload on hackage dates back to 2020-05-23 so this patch
is not included. You should probably install by cloning the repo
(or even move to idris2 because idris is not really maintained
anymore).

**Comment by fedeinthemix** [comment]
Thanks for the info. Is it possible to update idris on Hackage with the latest patches?

**Pull request merged**
