### PR TITLE
Fix compatibility with cheapskate-0.1.1

### PR DESCRIPTION
**Pull request by felixonmars**
Only define instances for older cheapskate

### CODE REVIEW

**Comment by david-christiansen** [comment]
Do we need to keep compatibility with older Cheapskate versions? Is there e.g. a GHC  or Stack snapshot support issue with the newer version that prevents us from requiring it instead?

**Comment by felixonmars** [comment]
I don't need it, just thought that it won't harm. I can surely remove it if you want :)

**Comment by ahmadsalim** [comment]
@marcelinevq recently patched cheapskate so it does not add extra dependencies, which it did for older versions of cabal and stack. Maybe we should rely on the latest version in this patch.

**Comment by felixonmars** [comment]
The latest version is 0.1.1 which is already required in this patch. Are you referring to an unreleased version?

**Comment by ahmadsalim** [comment]
@felixonmars Oh, it is the correct version!

**Comment by melted** [comment]
Thanks!

**Pull request merged**
