### PR TITLE
Effectful Logging.

### PR DESCRIPTION
**Pull request by jfdm**
Two logging effects with appropriate tests and documentation have been added.
These effects provide:

1. A Simple logger that provides logging in effectful functions based
   on numerical levels of verbosity.
2. A more advanced logger that adds categorisation of logging statments in
   addition to levels.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Would you mind rebasing? That ought to trigger Travis again as well.

**Comment by jfdm** [comment]
@david-christiansen I rebased this morning, but will try again to see if that retrogress travis

**Comment by david-christiansen** [comment]
Thanks! Sorry for the bother!

**Comment by jfdm** [comment]
*restarts travis. I think I may have pushed the wrong thing. Any who travis is working again.

**Comment by david-christiansen** [comment]
Thanks again!

**Comment by jfdm** [comment]
This is failing because my tests are failing will fix and push an update ASAP.

**Comment by jfdm** [comment]
For somer reason, this PR si failing although the code works. Maybe i did't do the tests correctly. I have pushed the code to an [external repo](https://github.com/jfdm/idris-logging) in the meantime.

**Comment by melted** [comment]
I think the problem is that the files in libs doesn't get added to the sdist, see the Extra-source-files section in idris.cabal.

**Comment by jfdm** [comment]
Ah the actual source files themselves...arg I am an idiot. Cheers @Melvar

**Pull request merged**
