### PR TITLE
Tiny spelling tweak.

### PR DESCRIPTION
**Pull request by steshaw**

### CODE REVIEW

**Comment by jfdm** [comment]
@steshaw Thanks for the PR, you appear to be on a roll. 

Travis is failing due to an issue not related to your PR, so please do not worry about Travis not completing. This is happening across a few other PRs at the moment.

While this is a useful PR to have, we are currently in the process of evaluating a contribution that rebases the testing suite on tasty and makes significant changes to the contents of `runtest.hs`. See #3231. 

Once travis has been sorted, we will come back to this PR.

**Comment by steshaw** [comment]
No worries and thanks for the heads-up.

**Comment by jfdm** [comment]
@steshaw The new test suite is in place, and sadly the problem you have fixed is no longer a problem. Sorry about that. I am going to close this issue now. 

Thanks for the contribution though!

**Comment by steshaw** [comment]
Hah, no worries ;)

**Pull request closed without merging**
