### PR TITLE
added require for the %lib anotations in js backend

### PR DESCRIPTION
**Pull request by rbarreiro**
to solve issue #3697

### CODE REVIEW

**Comment by melted** [comment]
Seems like travis is timing out, that probably just a travis problem.

**Comment by melted** [comment]
Thanks for the PR!

**Comment by jfdm** [comment]
Can the CHANGELOG be updated please? Also if there is other documentation that requires changing, can that be seen to as well.

**Comment by rbarreiro** [comment]
This feature was already documented, by error it was left out on the recent improvements to us backend, I noticed it by reading an issue it had on the previous implementation. So I think this is just a bugfix.

**Comment by jfdm** [comment]
No worries. Thanks

**Pull request merged**
