### PR TITLE
Add flatten to Monad.

### PR DESCRIPTION
**Pull request by ziman**
Per request on the mailing list. Stdlib compiles, tests pass.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Why did you choose to call it `flatten` rather than `join`? Most of the library adopts names from Haskell.

**Comment by ziman** [comment]
I didn't choose the name, I just moved the function into the interface.

Shall we rename it and add an alias, like with `return`?

**Comment by david-christiansen** [comment]
I think so, unless someone else has a good reason for this naming.

**Comment by Melvar** [comment]
IIUC it was named that way because at some point there were Algebra classes including `Joinsemilattice` which defined `join`. I am in favor of using `join` for the monad meaning now that those are out of the way.

**Comment by sellout** [comment]
Do we need to leave `flatten = join` somewhere to avoid breaking existing user code? And why use `(\y => y)` rather than `id`?

Otherwise, I strongly approve.

**Comment by david-christiansen** [comment]
There should probably be a deprecated top-level defn along the lines of:
```
%deprecated
flatten : Monad m => m (m a) -> m a
flatten = join
```

**Comment by jfdm** [comment]
@david-christiansen Do you not mean:

```
flatten : Monad m => m (m a) -> m a
flatten = join
%depreated flatten "..."

**Comment by david-christiansen** [comment]
Probably. I seem to be constitutionally unable to remember that syntax.

**Pull request merged**
