### PR TITLE
Improve interaction between Command Line Options and Package File Options.

### PR DESCRIPTION
**Pull request by jfdm**
Package Options are now influenced by command line options.

This PR addresses in part: #1448, and #499.

When building packages preapproved command line options (if
specified) will be merged into the options list generated from the
iPKG file. The allowed options are placed at the head of the options
list. The allowed options are:

+ Logging levels
+ Default total, default partial
+ Warn partial
+ Warn reach
+ Location of IBC subdir
+ Location of import dir.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Sounds good!  You're on a roll today!

What's the reasoning behind silently removing invalid options when merging option lists, as opposed to halting and informing the user? It seems like the latter is less likely to be surprising, but there may be some reason that I'm not seeing.

**Comment by jfdm** [comment]
Well, I wasn't sure how best to report any arising 'merge conflicts', given how the code is currently structured. My knowledge of haskell and the idris internals is murky.

**Comment by jfdm** [comment]
Also I will add, I also wasn't sure what should constitute a merge conflict.

**Comment by david-christiansen** [comment]
It would probably require a bit of a refactor - what I would do is put `buildPkg` and `mergeOptions` into the `Idris` monad, instead of the current respective `IO` and pure contexts, and then use `filterM` to conditionally remove elements, throw errors, or keep them.

**Comment by david-christiansen** [comment]
I think it's fine for package options to override certain options - that should make sense. But there's a call to `filter` that silently discards some options - that's what seems like it should return an error to me.

**Comment by david-christiansen** [comment]
(instead of using the `Idris` monad for error handling, `mergeOptions` could also return `Either Err [Opt]`, and then the callers could deal with the `Err` how they wanted - this might be cleaner, because `buildPkg` could stay in `IO` if that's where it really belongs)

**Comment by jfdm** [comment]
Both options sound good. I was thinking of going the `Either` route as I wasn't sure if the package commands should be integrated into the Idris monad.

**Comment by jfdm** [comment]
Well that went horrible wrong.

**Pull request closed without merging**
