### PR TITLE
added ST.Random utilitary functions

### PR DESCRIPTION
**Pull request by rbarreiro**
Added
+ rndInt
+ rndFin
+ rndSelect'
+ rndSelect

### CODE REVIEW

**Comment by Melvar** [comment]
`rndSelect` should probably require `NonEmpty` and leave off the `Maybe`.
Also, documentation is in Markdown, I’m not sure what you thought it was.

**Comment by rbarreiro** [comment]
This is a copy of Effects.Random

I can try to switch to NonEmpty instead of Maybe.
Regarding de documentation I just copy pasted it, what is wrong with it?

**Comment by ahmadsalim** [comment]
@rbarreiro Please change to `NonEmpty` instead.

I can't see what is immediately wrong with the documentation.
@Melvar can you please provide a hint there?

**Comment by Melvar** [comment]
```
Generate a random number in Fin (S `k`)
```
This uses backticks on only a variable name, rather than the entire code span `Fin (S k)`, suggesting the person writing it was expecting them to mean something different than they mean in Markdown. Other code spans are not marked up at all.

**Comment by ahmadsalim** [comment]
Thanks

**Pull request merged**
