### PR TITLE
changed js backend to look for includes also in getIdrisLibDir

### PR DESCRIPTION
**Pull request by rbarreiro**
Changed js backend to look for includes also in getIdrisLibDir. This is useful to use with objs ipkg option when making libraries. Without this I don't know any other way to include javascript parts on idris libraries.

### CODE REVIEW

**Comment by melted** [comment]
Rerruning CI

**Comment by ahmadsalim** [comment]
@rbarreiro Why are you closing and reopening the PR? :)

**Comment by rbarreiro** [comment]
To rerun travis.

**Comment by rbarreiro** [comment]
It is timing out a lot. I think we should start thinking of a way to solve that problem, Travis jobs are close to the 50 min timeout and lately are timing out a lot.

**Comment by ahmadsalim** [comment]
Maybe we should consider switching to something like Circle CI or privately hosted Jenkins instead.

**Comment by ahmadsalim** [comment]
Alternatively, we should put effort in optimizing the Idris build process. I actually like that idea much more :)

**Pull request merged**
