### PR TITLE
replace count use enumFromTo and enumFromThenTo in docs

### LINKED ISSUE #3183: 'count' needs updating in docs
Working through the Idris tutorial I came across a reference to `count` in [list comprehensions](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#list-comprehensions) (also on [the repo](https://github.com/idris-lang/Idris-dev/blob/master/docs/tutorial/typesfuns.rst#list-comprehensions)). I couldn't find this function in the current Prelude, but, after some digging around found it had been replaced with the `enumFrom` family.

It'd be nice to just reword the docs to say `enumFrom` instead but... There's a few variants, none of which seem to entirely replace the function; perhaps ```using the `enumFrom` family of functions from the prelude```?

### PR DESCRIPTION
**Pull request by zjhmale**
Fixes #3183

### CODE REVIEW

**Comment by jfdm** [comment]
@zjhmale Thanks for this. Normally, I am more astute with fixing minor documentation issues hat have been reported.

Cheers.

**Comment by zjhmale** [comment]
@jfdm ok, maybe i can search the issue list and fix more complicated ones after passing the GRE test 😂

**Comment by david-christiansen** [comment]
@zjhmale Good luck on the test!

**Comment by zjhmale** [comment]
@david-christiansen thx!!!

**Pull request merged**
