### PR TITLE
Update error message in reg050 from PR #1938

### PR DESCRIPTION
**Pull request by david-christiansen**
To get this ready for merging, a conflict had to be resolved.

### CODE REVIEW

**Comment by Melvar** [comment]
Should the prefix-like sigils (`!`, `?`, `@`, `~`) not be in that list?

**Comment by david-christiansen** [comment]
Possibly!

**Comment by david-christiansen** [comment]
@ahmadsalim I merged this to prevent nasty conflicts from coming with the next merge from the new tactics branch, but what do you think about @Melvar's question?

**Comment by ahmadsalim** [comment]
@Melvar @david-christiansen I think it is reasonable, to want to have these as invalid operators since the way we parse tokens now (if it was like Agda then it would have been different).

However, this also brings to light how to better handle invalid operators and such, but that can be handled in a different commit.
I will take a look and provide a new PR when I have time.

**Pull request merged**
