### PR TITLE
Annotate the Prelude with %used for backends

### PR DESCRIPTION
**Pull request by lenary**
This is my answer to #2743.

Not all the tests pass. There's a funny interaction with '%name' that prevents interactive things passing, and of course the Quasiquotation tests fail because some of the code has changed. I'd appreciate some help deciding which of those tests are now wrong, and which are really failures.

### CODE REVIEW

**Comment by melted** [comment]
I don't think I'm able to help with the quasiquoter. I wonder about the primitives002 test though, it just seems to crash and burn.

**Comment by lenary** [comment]
@melted I think the quasiquoter expectations just need to be updated, but would like some confirmation from @david-christiansen (or someone else who knows the system well enough to know whether i've broken it).

As for primitives002, I'll take a look, though I'm somewhat surprised I broke it, given I don't think I have code that interacts with it.

**Comment by david-christiansen** [comment]
The quasiquote test outputs shown in Travis are fine - just update the output with the new expected information. The quoted forms show the names bound in Pi, which you've modified from an MN to a UN, and this is reflected in the output. Just go into the test directory and type `./run > expected`.

**Comment by lenary** [comment]
Ok, so, tests pass, though there's the weird "killed…" message in the output, which I think is from something else entirely.

**Comment by edwinb** [comment]
I'm slightly scared by the "killed" message. I've restarted the tests on the off chance it was some one off travis thing, but the fact that there's a message but the tests report success is a bit worrying. I'd like to at least work out where the message came from before merging...

**Comment by lenary** [comment]
It seems to be coming from this: https://github.com/idris-lang/Idris-dev/blob/master/test/meta002/Deriving.idr

The same 'killed...' message is happening in the master branch builds: https://travis-ci.org/idris-lang/Idris-dev/jobs/88681037#L1396

**Comment by lenary** [comment]
I'm going to open a new ticket for that "killed…" message, as it's totally orthogonal to this pull request. I've been doing a little analysis, and think I've nailed down the cause of it.

**Comment by david-christiansen** [comment]
I don't think there's anything blocking this, but I don't want to push "merge" due to not being entirely sure about the erasure mechanism and backends. If @ziman or @edwinb says "go", I'm happy to do it.

**Comment by ziman** [comment]
I don't think this will break anything.

**Comment by edwinb** [comment]
Done. Sorry for slowness.

**Pull request merged**
