### PR TITLE
Rewrite fib with provably equivalent tail recursive definition

### PR DESCRIPTION
**Pull request by nickdrozd**

### CODE REVIEW

**Comment by nickdrozd** [comment]
@melted Could you take a look? This is an easy one, I hope :)

**Comment by msmorgan** [comment]
I tried doing this previously in #4216, but my change was turned down because it's a breaking change in prelude.

**Comment by melted** [comment]
This doesn't use default implicits though.

Frankly, I have no idea why fib is in the prelude at all. That split will be way better in Idris 2 :-)

**Comment by nickdrozd** [comment]
I don't particularly care how the function is implemented in the prelude (why is it defined there at all???), so I've amended this PR to only add a proof that recursive and iterative Fibonacci are equivalent without any reference to the "official" `fib` function.

**Comment by nickdrozd** [comment]
The build failure looks unrelated.

**Comment by melted** [comment]
Looks good!

**Pull request merged**
