### PR TITLE
[ fix #4304 ] Make the Module Name parser explicit

### LINKED ISSUE #4304: idris --install: "Uncaught error: [filepath] copyFile: does not exists"
The issue is that the parser uses [`iName`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Package/Parser.hs#L120) (that is an `identifier`) to parse a module's
file name but it may not be a valid one (e.g. it can use a reserved keyword such as
`Type` in `Data.Tree.Type`).

### PR DESCRIPTION
**Pull request by gallais**
and share it between Idris.Parser and Idris.Package.Parser

### CODE REVIEW

**Comment by ahmadsalim** [comment]
Thanks!

**Comment by gallais** [comment]
There seems to be an issue with the test case on windows: the `expected` file
contains paths which use `/` as their delimiters but on windows the delimiter is
`\`. Is there a canonical way of dealing with this in the test-suite?

**Comment by ahmadsalim** [comment]
@melted Any idea? ^

**Comment by melted** [comment]
The test runner should disregard the difference between / and \. So it’s a bit weird.

**Pull request merged**
