### PR TITLE
Tidy stderr output from base001

### PR DESCRIPTION
**Pull request by steshaw**
Avoid having expected errors appear on stderr (in the build log).

Before:

```sh-session
steshaw@paris:~/Projects/idris/test/base001 git:(master) 
$ stack test --test-arguments '-p base001'                                              <<<
idris-0.12.2: test (suite: regression-and-feature-tests, args: -p base001)

Regression and feature tests
  Base
    base001: 
Error: test/base001
sh: 1: ./does-not-exist: not found
sh: 1: ./does-not-exist: not found

OK (7.64s)

All 1 tests passed (7.70s)
```

After:

```sh-session
steshaw@paris:~/Projects/idris/test/base001 git:(tidy-stderr-output-from-base001) 
➯ stack test --test-arguments '-p base001'                                              <<<
idris-0.12.2: test (suite: regression-and-feature-tests, args: -p base001)

Regression and feature tests
  Base
    base001: OK (7.87s)

All 1 tests passed (7.95s)
```

### CODE REVIEW

**Comment by melted** [comment]
Please rebase this on master (see commitlist)

**Comment by steshaw** [comment]
@melted, those commits don't really look familiar for this pull request :). Do you know what happened there?

**Comment by steshaw** [comment]
Ah, that's better :D. All rebased.

**Comment by melted** [comment]
Thanks!

The reason was that I pushed bad things to master by mistake and had to rewrite history.

**Comment by steshaw** [comment]
@melted ah, no worries!

**Pull request merged**
