### PR TITLE
Fix LaTeX pretty printing of backslash, braces and percent

### LINKED ISSUE #1876: Pretty print produces invalid LaTeX for anonymous functions.
The following `Idris` snippet:

``` idris
mkNodeList : List (Document a) -> {auto prf : ValidNode a} -> List $ Document NODE
mkNodeList Nil = Nil
mkNodeList xs = map (\x => Node x) xs
```

when pretty printed using `:pp latex 80`, produces invalid LaTeX for the Verbatim mode used. This is a result of command chars being specified using `commandchars=\\\{\}`. As a result braces and backslashes, used in implicit arguments and anonymous functions, cause Verbatim to think there is a LaTeX command. 

The fix will be to ensure that braces are escaped properly (`\{auto implic\}`), and backslashes are created using the `\textbackslash{}` command.

### PR DESCRIPTION
**Pull request by joom**
Resolves #1876.

I'm not sure about the `toSExp (AnnSyntax c) = SexpList []` part so I need feedback on that.

### CODE REVIEW

**Comment by joom** [comment]
Following @ahmadsalim's suggestion, I tried writing a test for this, but my test failed. When I diff the output and the expected, I get this:
```
15c15
< \begin{Verbatim}[commandchars=/\{\}]
---
> \begin{Verbatim}[commandchars=\\\{\}]
```

That is unusual because even when I do `./run > expected` and then run the tests, I get the same result. In other words, the problem is not with my code or the test I wrote, but with the testing system itself. Then I discovered [the `normalise` function in `TestRun.hs`.](https://github.com/idris-lang/Idris-dev/blob/4e00dc2fa433ae6d58310fda0e1f4e9a234f3ecd/test/TestRun.hs#L99-L104) I can't think of any way of bypassing it with small changes to `TestRun.hs`. Any suggestions?

I also don't think testing pretty printed code generation makes much sense, given that even changes to the CSS in the HTML, or spacing in LaTeX command definitions can break the test.

**Comment by ahmadsalim** [comment]
@joom Hmm, the `normalize` function seems a bit weird indeed.

OK, I will merge your PR without a test then. Perhaps, just an update to the CHANGELOG please? 😄

**Comment by melted** [comment]
Normalize just makes filepaths compare the same. If you create the expected with update it's automatically taken into account.

**Comment by joom** [comment]
@melted Does creating the expected with update mean manually changing `\\\` to `/` in every pretty printing test? I think that might get confusing in the future for other people who might want to write more pretty printing tests.

I updated the changelog. I haven't added the test yet, but I can if you think what I said above seems fine to you.

**Comment by david-christiansen** [comment]
Interesting solution, using the annotation system. I hadn't thought to do it that way.

Can we use this annotation for anything else that's interesting? E.g. balancing delimiters in console output a la Emacs's rainbow parens?

**Comment by melted** [comment]
@joom I don't think a test is required here., so I'll merge. 

It used to be that the normalization was done on both expected and output when they were compared. So I'm a bit surprised that there is a problem with it.

**Pull request merged**
