### PR TITLE
Use a modern ghc for appveyor

### PR DESCRIPTION
**Pull request by melted**

### CODE REVIEW

**Comment by melted** [comment]
We should create a ghc 8.2 target for travis too.

**Comment by melted** [comment]
Ok, so pkg004 flakes out. I can see that locally too.

**Comment by eraserhd** [comment]
@melted 
Haha, this error is expected, I think.  Because it's checking whether there are any system directory separators, and apparently in the new GHC, "/" is not a system directory separator, and the backslash in `test/pkg004/test.ipkg` is escaping the "a" and is therefore an "invalid character".

It should pass if you push a commit doubling the backslash.

**Comment by melted** [comment]
Fixed in #4170

**Pull request closed without merging**
