### PR TITLE
Language.JSON: total JSON parsing

### PR DESCRIPTION
**Pull request by msmorgan**
At the moment, does not display parse errors to the user (that is, `parse` returns `Maybe JSON`).

### CODE REVIEW

**Comment by jfdm** [comment]
I think it would be prudent to split this into two PRs: one with the changes to the Lexer and Parser; and the other with the JSON parser contributions. 

There are one or two things in the changes to lexer/parser libraries that at first glance would require some further thought, and I want to consider it for a little before merging or not.

**Comment by msmorgan** [comment]
@jfdm Can do.

Additionally, I'm running into an error with what I thought would be "private" modules. Several of the submodules in Language.JSON are deliberately not included in contrib.ipkg, since a user of the contrib library would likely not want to import them alone.

However, without these packages in the ipkg, the following error occurs when a build is attempted.

```
$ idris -p contrib -o main Main.idr
idris.exe: Erasure/getArity: definition not found for Language.JSON.Lexer.lexJSON
CallStack (from HasCallStack):
  error, called at src\Idris\Erasure.hs:602:20 in idris-1.1.1-6LYZyZduqp2CPjeZoUWKa1:Idris.Erasure
```

To fix this, I'll add the missing modules to the ipkg, and potentially merge them together at a later time.

Is this intended behavior?

**Comment by jfdm** [comment]
One thing to note, if a module is not listed in the ipkg file then it is not installed.

**Comment by msmorgan** [comment]
@jfdm I opened a PR on my own fork, with a version of this library that doesn't require Text.Token.

https://github.com/msmorgan/Idris-dev/pull/5

I wrote it as a basis for comparison, but if you prefer that version I can update this PR with that code.

**Comment by ahmadsalim** [comment]
@msmorgan Can you please rebase this on `master`? 😄

**Comment by msmorgan** [comment]
I've rebased onto master, and cleaned up the history a bit.

**Comment by ahmadsalim** [comment]
@msmorgan Since @jfdm approved merging this when ready, I will merge it now 😄.
Thanks again for the PR!

**Pull request merged**
