### PR TITLE
Make totality checker to report partial functions correctly (fix #2884)

### LINKED ISSUE #2884: Totality checker reports partial function as total
Code:

```idris
module TotalityBug

%default total

-- Idris thinks this function is total
g : (Bool, Bool) -> Bool
g (True, x) = True
g (x, True) = True
```

Test:

```
$ idris --version
0.9.20.2
$ idris
Idris> :load TotalityBug
*TotalityBug> :total g
TotalityBug.g is Total
*TotalityBug> g (True, False)
True : Bool
*TotalityBug> g (True, True)
True : Bool
*TotalityBug> g (False, True)
True : Bool
*TotalityBug> g (False, False)
g (False, False) : Bool
```

### PR DESCRIPTION
**Pull request by bravit**
Totality checker incorrectly reported some partial functions with complex
arguments (data constructors inside other data constructors) as total.
For example, these functions were considered total:

```idris
h : (Bool, Bool) -> Bool
h (True, x) = True
h (y, True) = True

data PP : Type where
  MkPP : Int -> PP

f : PP -> Bool
f (MkPP 0) = True
f (MkPP 1) = True
f (MkPP 2) = True
```
This commit fixes this and now such functions are reported as partial.
To fix this we generate more clauses which cover more possible cases.

### CODE REVIEW

**Comment by jfdm** [comment]
@bravit Thanks for the contribution to the project, it is much appreciated. It appears that AppVeyor has failed due to a timeout on its end, and nothing to do with your contribution. Travis passed all its tests. 

I shall look at merging this tomorrow, however, someone else might beat me to it. Please do add yourself to `CONTRIBUTORS.md`.

**Comment by melted** [comment]
I have fixed Appveyor in master.

**Comment by jfdm** [comment]
For @bravit, apparently there was a mishap in master and the commit history of master was modified unintentionally. Is it possible for you to rebase of master just to get this PR back on track? Apologies for any inconvenience.

**Comment by melted** [comment]
Thanks for the PR!

**Pull request merged**
