### PR TITLE
make lines and unlines agree with Haskell

### LINKED ISSUE #3278: lines/unlines disagree with Haskell
The prelude functions `lines` and `unlines` disagree with the way they are specified for Haskell. I figured that was unintended.

- `lines` does not cope with trailing newline correctly. i.e. `lines "\n\n" != ["", ""]`.
- `unlines` does not newline terminate each line before concatenating.

### PR DESCRIPTION
**Pull request by zjhmale**
Fixes #3278

### CODE REVIEW

**Comment by zjhmale** [comment]
poke @jfdm

**Comment by melted** [comment]
Thanks for the PR!

**Comment by steshaw** [comment]
Thanks @zjhmale!

**Comment by zjhmale** [comment]
@steshaw my pleasure 😄

**Pull request merged**
