### PR TITLE
Prelude.Nat: add IsSucc predicate type

### PR DESCRIPTION
**Pull request by msmorgan**
By popular demand.

If this should be moved to `Data.Nat` in `base`, say the word. There is no
such module at the moment, however.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@msmorgan Thanks!

Can you move it under syntactic tests please? Now it is under comparisons.

**Comment by ahmadsalim** [comment]
Also, please add an entry to the changelog

**Comment by msmorgan** [comment]
@ahmadsalim Can do. My rationale for putting it where I did is that it's comparing to zero, and its function is very similar to NotBothZero.

**Comment by ahmadsalim** [comment]
@msmorgan I would still prefer the former please :).
I do not think it is strictly a comparison.

**Pull request merged**
