### PR TITLE
Revert "Merge pull request #3896 from melted/codegen_rws"

### PR DESCRIPTION
**Pull request by melted**
This reverts commit e471a1c8f76ae90492027001124471f70086de98, reversing
changes made to f2c4091990e0ad2629d18480b6a3b1a582dcb7e0.

Reverts #3896 because of the performance hit

### CODE REVIEW

**Comment by melted** [comment]
Funny thing is that build isn't sped up an appreciable amount, previous builds took 32-33 minutes on Appveyor, these took 32:04 and 32:39. One would think such a big performance hit would be noticeable in 200+ tests.

**Comment by jfdm** [comment]
Please note that in @edwinb's original comment the performance hit was found with code of 'significant size'. I doubt the size of the program's that constitute Idris' test suite are comparable to the size of program that the performance regression was encountered.

**Comment by melted** [comment]
Just one travis build timed out, let's merge!

**Comment by edwinb** [comment]
Yes, I suspect it only really starts to hurt for programs much larger than the test suite. Although the program in question isn't that large - just about 3500 lines. Anyway, the offending function doesn't even register in the profile now, so that's reassuring.

**Pull request merged**
