### PR TITLE
Use GHC generics for NFData instances

### PR DESCRIPTION
**Pull request by enolan**
This gets rid of a lot of code. Much of it was generated with
the "derive" tool, but some of it wasn't. I tested compilation speed
by compiling the benchmarks with bench[1] and there was no
statistically significant difference.

[1]: https://github.com/Gabriel439/bench

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@enolan Would it be possible to also do this for `Binary` and the other things that used derive?

**Comment by melted** [comment]
I'd be careful with Binary, it's much slower with Generic and what we have is unacceptably slow as is.

**Comment by enolan** [comment]
@ahmadsalim It's possible, yes. I was planning to look into after this one. If benchmarking shows a substantial performance degradation then we shouldn't do it.

Do you want me to handle Binary before merging this PR?

**Comment by ahmadsalim** [comment]
@enolan Oh, not necessarily. I was just wondering whether it was possible.

**Comment by melted** [comment]
The PR is fine as is. 

I'm unhappy with Binary. The loading is slow and generates way more garbage than reasonable. I'd rather try to find a better way to do the IBCs

**Comment by melted** [comment]
Thanks for the PR!

Stats of +202-1045 means you owe us 843 lines of code :-)

**Pull request merged**
