### PR TITLE
Fix substitution when applying syntax rules

### LINKED ISSUE #1283: A few things don’t work inside syntax
Using a syntax rule with a do block on the RHS causes a crash because [`Idris.ParseExpr.extension where update where upd`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/ParseExpr.hs#L175-L185) is missing a case for `[]`. This is how I found this problem.

Additionally, [`Idris.ParseExpr.extension where update`](https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/ParseExpr.hs#L155-L187) does not have a case for `PDisamb`, so using a syntax rule that mentions a syntax-bound variable within a `with NS expr` expression causes a “no such variable” error, because the said variable isn’t being replaced when the syntax rule is applied. The same appears to be true of `PRefl`, `PEq`, `PRewrite`, `PIdiom`, `PProof` and `PTactics`. I could probably fix these, but there are a few more constructors I can’t identify immediately, so I decided to report first in case one of the rest also needed to be `update`d under.

### PR DESCRIPTION
**Pull request by Melvar**
Fixes #1283

### CODE REVIEW

**Comment by Melvar** [comment]
Kinda baffled about this test failure.

**Comment by david-christiansen** [comment]
I re-ran the failing test, and now it's fine. Huh.

**Comment by Melvar** [comment]
See perhaps also https://github.com/idris-lang/Idris-dev/commit/46bdfa9b897f2ac487a0f6e313aa73ce2f61a48a . It’s a TCon number varying for some reason it seems.

**Comment by david-christiansen** [comment]
Thanks for all your hard work on this! It looks good to me.

**Pull request merged**
