### PR TITLE
Improve universe solver

### PR DESCRIPTION
**Pull request by ozgurakgun**
I have done a few obvious things to hopefully improve the performance a bit. Happy to look at this again later if I can get my hand on a tricky problem to do with universe checking.

The error message for error001 is changed due to the order of constraints. This is expected.

The error message should probably be updated not to print that much info anyway.

### CODE REVIEW

**Comment by edwinb** [comment]
Thanks for this! I was tinkering with the solver most of yesterday (mostly trying to reduce the number of constraints it gets) and this certainly speeds things up.

There's still the odd pathological case - Control.Arrow in base is currently taking about 33 seconds to check, for me. But when I try to profile it, its suddenly fast, so I'm wondering if that's something odd at my end instead.

**Comment by edwinb** [comment]
One question - if we made a better effort to put concrete levels in (a lot are obviously just 0 for example) and allowed users to make levels explicit, would this have a significant effect on the speed of the solver?

Important as it is, it does seem to be a bottleneck so if we can give it help and have it run much faster that'd be great!

**Comment by ozgurakgun** [comment]
I will take a look at what happens with `Control.Arrow`, probably tomorrow.

Setting variables to 0 if they are known to be 0 should help. `x <= 0` will only be propagated once, so that's good.

There are also other things we can do to improve the performance. I started with a simple implementation hoping that it would be fast enough already. We can keep adding tricks gradually until it is fast enough. :)

**Comment by edwinb** [comment]
It turns out that the problem is simply that constraintsLHS and constraintsRHS aren't cached like you'd expect, since they're in a where clause and built every time. Possibly a different set of optimisations would do this, but I've just cached them explicitly in the state and suddenly it's running more or less instantly. Yay!

**Comment by ozgurakgun** [comment]
Oh *that* is great news! :)

Haskell's performance characteristics still manage to puzzle me.

**Pull request merged**
