### PR TITLE
Add IRC badge for #idris channel

### PR DESCRIPTION
**Pull request by ahmadsalim**
It uses IRCClouds abilities to add a badge that links directly to our IRC channel.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Why not link to Freenode's Web client instead?

**Comment by ahmadsalim** [comment]
@david-christiansen Does it have a badge? :)

**Comment by ahmadsalim** [comment]
Ah, I see that the badge is general. Hmm, I only discovered this badge via IRCCloud, so I didn't know that I could use other websites.

**Comment by ahmadsalim** [comment]
What is the general preference?
So IRCCloud is freemium and allows you to use the webclient for free and even keep being logged on for 2 hours, but does require you to register a user.

The Freenode web-client is more limited, but does not require registration.

**Comment by ahmadsalim** [comment]
Also, you can open this link in other clients than just IRCCloud.

**Comment by zjhmale** [comment]
Personally, i think link to IRCCloud is cool enough :)

**Comment by Melvar** [comment]
The most generic solution is to use the actual `irc:` scheme, `irc://chat.freenode.net:6667/idris` would then be correct if I am not mistaken. Arguments about newbie-friendliness may apply.

**Comment by Melvar** [comment]
@ahmadsalim I’m not sure how one would open the IRCCloud link in other clients.

**Comment by ahmadsalim** [comment]
@Melvar You can try the link here: https://www.irccloud.com/invite?channel=%23idris&hostname=irc.freenode.net&port=6697&ssl=1 .

**Comment by ahmadsalim** [comment]
Basically, it has a blue "join us" button, and a "join with another client" link just underneath that follows the IRC protocol.

**Comment by Melvar** [comment]
Oh, on the page this links to, rather than this itself. Okay.

**Comment by ahmadsalim** [comment]
@david-christiansen Any objections on using IRCCloud link?

**Comment by ahmadsalim** [comment]
Otherwise I will just merge, if no one expresses their discontent in the near future

**Comment by melted** [comment]
I think IRCCloud is good, it should be easy for the uninitiated. Providing a hint about where it is to old IRC hands is a bonus.

**Comment by ahmadsalim** [comment]
I will merge, I asked @edwinb and he had no strong opinion on subject matter, and people seemed happy and non-objective. If @david-christiansen prefers something else when he gets back from vacation, we can always change it I guess.

**Pull request merged**
