### PR TITLE
Move `ignore` to Prelude.Functor

### PR DESCRIPTION
**Pull request by aiya000**
from Pruviloj.Core

### CODE REVIEW

**Comment by LeifW** [comment]
In Haskell, this is called `void` and `<$`; in the cats Scala lib, it's
called `as`.

On Feb 17, 2018 12:18 AM, "aiya000" <notifications@github.com> wrote:

from Pruviloj.Core
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/idris-lang/Idris-dev/pull/4335
Commit Summary

   - Move `ignore` to Prelude.Functor

File Changes

   - *M* libs/prelude/Prelude/Functor.idr
   <https://github.com/idris-lang/Idris-dev/pull/4335/files#diff-0> (4)
   - *M* libs/pruviloj/Pruviloj/Core.idr
   <https://github.com/idris-lang/Idris-dev/pull/4335/files#diff-1> (4)

Patch Links:

   - https://github.com/idris-lang/Idris-dev/pull/4335.patch
   - https://github.com/idris-lang/Idris-dev/pull/4335.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/idris-lang/Idris-dev/pull/4335>, or mute the thread

**Comment by LeifW** [comment]
Err, only void is this, sorry - the other two are `fmap . const`.

**Comment by aiya000** [comment]
@LeifW Should I rename to 'void'
and change definition to `fmap . const`? :smile:

**Comment by ahmadsalim** [comment]
@aiya000 @LeifW `void` is `Void -> a` in Idris.

**Comment by ahmadsalim** [comment]
@aiya000 You don't need to change the definition, but you can change it to `map . const ()` if you like.

**Comment by ahmadsalim** [comment]
Actually, it is `map (const ())`

**Comment by aiya000** [comment]
@ahmadsalim Thanks!
I feel no changing is needed :D

**Comment by ahmadsalim** [comment]
Thanks for the PR ! :)

**Comment by aiya000** [comment]
Thanks too 🐕 ✨

**Pull request merged**
