### PR TITLE
Fix Windows RTS

### PR DESCRIPTION
**Pull request by melted**
Fixup idris_writeStr (with name change)

Add the functionality to fpoll.

### CODE REVIEW

**Comment by Heather** [comment]
That should be: https://github.com/idris-lang/Idris-dev/issues/1935

**Comment by Heather** [comment]
@edwinb please review it as high priority task :+1:

**Comment by jfdm** [comment]
I am wondering if it is possible if the PR author could kindly add a bit more information over what the PR is doing, and why it should be considered. This way we can be in a better position to review the PR.

**Comment by melted** [comment]
A function was renamed and added a return value in the rts. I propagated that change to the windows version of the file, which was necessary.for Idris to work. I also added an implementation to fpoll.



----- Ursprungligt meddelande -----
Från: "Jan de Muijnck-Hughes" <notifications@github.com>
Skickat: ‎2015-‎02-‎23 10:40
Till: "idris-lang/Idris-dev" <Idris-dev@noreply.github.com>
Kopia: "Niklas Larsson" <metaniklas@gmail.com>
Ämne: Re: [Idris-dev] Fix Windows RTS (#1939)

I am wondering if it is possible if the PR author could kindly add a bit more information over what the PR is doing, and why it should be considered. This way we can be in a better position to review the PR.

**Comment by david-christiansen** [comment]
I'm not in a good position to test this out, TBH, so I'll trust @melted :-) He's done good stuff before!

@melted: can we perhaps talk on IRC sometime about how we could potentially get Idris for Windows testing on Appveyor, kind of like we have on Travis for Linux and hopefully also someday Mac OS?

**Pull request merged**
