### PR TITLE
Fix error message for unsuccessful namespace disambiguation

### PR DESCRIPTION
**Pull request by BartAdv**
The presented error message contained reversed namespace.

Also fix small typo in tests README.

### CODE REVIEW

**Comment by melted** [comment]
Didn't add the test to cabal, but as that has gone away, the only thing that needs to be done is to rebase this on master.

**Comment by BartAdv** [comment]
Yeah, finally I won't be keeping to forget about those files. Also, removed some irrelevant line from test README that was referring to extra files from idris.cabal.

**Comment by melted** [comment]
Please rebase this on master, I snarled up git a little.

**Comment by melted** [comment]
Thanks for the PR!

**Pull request merged**
