### PR TITLE
Allow ipkg sourcedir to have deep location

### PR DESCRIPTION
**Pull request by shmish111**
https://github.com/idris-lang/Idris-dev/issues/4618

### CODE REVIEW

**Comment by melted** [comment]
Hmmm.  Can we just read to the newline, trim whitespace and parse that as a path?

Thanks for the PR anyway!

**Comment by shmish111** [comment]
Good point @melted so I've implemented the easy option in this new commit. I find it quite normal to allow simple things unquoted and complicated things quoted.

**Comment by shmish111** [comment]
What tends to be the release schedule for Idris? Not being pushy here, just want to get some idea of how long bugs like this tend to get fixed. Also @melted is my PR ok now that I have enabled quoted and unquoted parsing?

**Comment by melted** [comment]
@shmish111 Work on Idris has slowed down (with all the effort Edwin is putting into Blodwen, Idris in Idris), but there have been several releases a year even so. But the exact timing depends on need, a new release of GHC usually provides motivation with breaking code.

**Comment by shmish111** [comment]
That's awesome thanks @melted

**Pull request merged**
