### PR TITLE
Implement shebang handling

### LINKED ISSUE #2247: Allow Idris source files to contain a shebang line
So idris source files can be made executable on unixy systems by putting `#!/bin/env runidris` on the first line.

This would also require a script/program `runidris` that works like `runhaskell`

### PR DESCRIPTION
**Pull request by melted**
Add two scripts for running idris programs with the C and node backends and adds a test.

Fixes #2247 

Implementation cribbed from #2289

### CODE REVIEW

**Comment by david-christiansen** [comment]
Where does Idris look for libraries when #!ing? I would think that in shebang mode, it should consider imports relative to the file being executed.

**Comment by melted** [comment]
@david-christiansen It's easy enough to put that into the command line in the scripts. For neatness, I should probably put the ibc files in the temp directory too.

It would be nice to have a directive so that the packages used could be specified in the source file. Here you can't put them on the command line, so it's a bit hamstrung without it. But I think that would be generally useful. If a program uses effects, putting `%package effects` in there is easier than remembering `-p effects` every time one builds it.

**Comment by melted** [comment]
Another thing to do is to pass the rest of the args into the program.

**Comment by david-christiansen** [comment]
It would indeed be nice to be able to configure packages in programs. The Emacs mode has a stupid hack for this that only works in Emacs, which bugs me.

In any case, I think this is worth a mailing list announcement :-)

**Comment by jfdm** [comment]
I'm not entirely convinced that a specific directive for packages is needed for 'Idris Scripts'. Such a `%package` directive might serve as a source of confusion when writing ordinary Idris Programs. That is, people might think that `%package` is required regardless. Maybe if suitable error messages and flags and warnings are present to enforce correct usage, then this approach might work.

I would much prefer t[he approach `stack` has taken with specifying packages in `Scripts`](https://haskell-lang.org/tutorial/stack-script) which requires passing of package imports as command line arguments in the file itself.

**Comment by melted** [comment]
Yeah, that's a good idea, that would mean I would have to rewrite runidris in something other than shell though :-)

**Comment by zenntenn** [comment]
Is there a reason it can't be set up to have the -p argument passed in on
the shebang line?

**Comment by melted** [comment]
The shebang line only takes one argument and if you use /usr/bin/env as is common that is taken by the executable. 

> 28 juli 2017 kl. 22:40 skrev zenntenn <notifications@github.com>:
> 
> Is there a reason it can't be set up to have the -p argument passed in on
> the shebang line?
>

**Comment by melted** [comment]
One thing that is possible is to let the runidris program filter the command line and extract ones marked in a special way (like ghcs +RTS) and pass them to idris. 

> 28 juli 2017 kl. 22:40 skrev zenntenn <notifications@github.com>:
> 
> Is there a reason it can't be set up to have the -p argument passed in on
> the shebang line?
>

**Comment by melted** [comment]
Having thought about it a bit more is that it would preferable to have a directive to pass general command lines inside a file. Stack does it in comments because GHC can't be expected to know about stack. We don't have that problem.

**Comment by david-christiansen** [comment]
Perhaps in Idris? [ducks]

On July 28, 2017 4:36:33 PM EDT, Niklas Larsson <notifications@github.com> wrote:
>Yeah, that's a good idea, that would mean I would have to rewrite
>runidris in something other than shell though :-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/idris-lang/Idris-dev/pull/3948#issuecomment-318755892

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by melted** [comment]
Now I'm actually tempted to do that. It should be easy enough.

**Pull request merged**
