### PR TITLE
Enable test interactive017

### PR DESCRIPTION
**Pull request by steshaw**
Just happened to notice that `interactive017` wasn't being run. I've added it to `TestData.hs` and `chmod +x` a couple of files to make it work.

### CODE REVIEW

**Comment by melted** [comment]
Thanks!

I wonder if we shouldn't tweak the test though. As it is now it always runs both node and C backend stuff. It would be more in line with the other tests if the run script checked if it was passed `--codegen node` and run node scripts  (they would have to have the same output as the C scripts).

**Comment by steshaw** [comment]
The idea of this pull request is just to enable the test. I see what you mean about the test being different to other tests.

**Comment by melted** [comment]
I'm mostly worried that it will fail in an environment without node even if run without "--codegen node".

**Comment by steshaw** [comment]
That makes sense. I've disabled the interactive017 again on my branch (just commented out in `TestData.hs`). I'm currently working on a solution for #1209 (where I'd added a interactive018 and noticed that interactive017 wasn't enabled).

**Pull request closed without merging**
