### PR TITLE
Fix for issue 3796 - 0/0 being compiled as -Infinity

### PR DESCRIPTION
**Pull request by edmundsmith**
This pull request is a fix for [issue 3796 - 0/0 being compiled as -Infinity](https://github.com/idris-lang/Idris-dev/issues/3796).

This changes the bytecode generation for doubles to preserve IEEE float special values, like NaN and Infinity. The existing generation uses `Data.Binary`'s included `instance Binary Double`, which uses `decodeFloat` and `encodeFloat` under the hood. This converts `Double`s to an `(Integer, Int)` and back, losing NaNs in the process.

Using the functions introduced in binary-0.8.4, full IEEE detail can be preserved throughout `Binary` encoding and decoding with `getDoublele` and `putDoublele`. This preserves NaNs and Infinities through the bytecode, fixing the issue.

By changing the encoding from `(Integer, Int)` to (effectively) `Word64`, existing ibc files will be invalidated by this patch. However, I think will be a necessary change to correctly represent and preserve IEEE double values.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
Thanks for the PR!
Please increment the number, so that Idris can figure out that the byte code version is wrong: https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/IBC.hs#L50

**Comment by edmundsmith** [comment]
It's been incremented

**Comment by edmundsmith** [comment]
CI is sometimes failing because it fails to install distributive-0.5.2 or it times out, other times it passes all the tests fine. What's the solution to this?

**Comment by melted** [comment]
The time out is just travis being flaky. 

I'm a bit worried about the ghc 7.6.3 not building though. Did one of our deps pull in something that's not compatible with that?

Anyway, I have restarted the failed builds

**Comment by edmundsmith** [comment]
It seems `unix-2.6.0.1` and `unix-2.7.2.1` are both installed and conflicted in the Travis ghc 7.6.3 build. I don't know what's causing both to be installed, however. Could this be a result of changing to `binary-0.8.5` in the patch?

**Comment by melted** [comment]
That's weird, binary doesn't depend on unix, and only depends on base, bytestring, arrays and containers, which shouldn't either. I can build this PR fine on 7.6.3, but that's on Windows.

**Comment by melted** [comment]
Can you try to pin unix to less than 2.7 if building for ghc less than 7.8? we have several such exceptions in idris.cabal already.

**Comment by ahmadsalim** [comment]
Maybe this is easier to make work now, since we dropped support for `< 7.10`?. @edmundsmith could you please check whether you can get it working now?

**Comment by edmundsmith** [comment]
@ahmadsalim The only errors are now for exceeding the time limit. Is this still blocking, and if so, how do I get around this?

**Comment by melted** [comment]
Travis has been slow for over a week. I'll merge this as soon as Edwin has made the point release to fix the cheapskate issue.

**Comment by melted** [comment]
Thanks for the contribution!

**Pull request merged**
