### PR TITLE
Parser traces

### PR DESCRIPTION
**Pull request by ziman**
With `--parsertrace`, you can get parser traces where the "checkpoints" are given by `<?>`:
```idris
$ cat impl.idr 
module impl

f : {x : Nat} -> Bool
f = True

$ idris --parsertrace --check impl.idr
Parser trace:
  impl.idr:1:8: identifier
  impl.idr:1:8: identifier
  impl.idr:3:1: function modifier
  impl.idr:3:1: function modifier
  impl.idr:3:1: function name
  impl.idr:3:1: name
  impl.idr:3:1: name
  impl.idr:3:1: identifier
  impl.idr:3:1: identifier
  impl.idr:3:5: type signature
  impl.idr:3:5: dependent type signature
  impl.idr:3:5: static modifier
  impl.idr:3:6: function name
  impl.idr:3:6: name
  impl.idr:3:6: name
  impl.idr:3:6: identifier
  impl.idr:3:6: identifier
  impl.idr:3:10: type signature
  impl.idr:3:10: dependent type signature
  impl.idr:3:10: static modifier
  impl.idr:3:10: expression
  impl.idr:3:10: expression
  impl.idr:3:10: function application
  impl.idr:3:10: function name
  impl.idr:3:10: name
  impl.idr:3:10: name
  impl.idr:3:10: identifier
  impl.idr:3:10: identifier
  impl.idr:3:18: dependent type signature
  impl.idr:3:18: static modifier
  impl.idr:3:18: expression
  impl.idr:3:18: expression
  impl.idr:3:18: function application
  impl.idr:3:18: function name
  impl.idr:3:18: name
  impl.idr:3:18: name
  impl.idr:3:18: identifier
  impl.idr:3:18: identifier
  impl.idr:4:1: function declaration
  impl.idr:4:1: pattern
  impl.idr:4:1: function clause
  impl.idr:4:1: function name
  impl.idr:4:1: name
  impl.idr:4:1: name
  impl.idr:4:1: identifier
  impl.idr:4:1: identifier
  impl.idr:4:5: dependent type signature
  impl.idr:4:5: static modifier
  impl.idr:4:5: expression
  impl.idr:4:5: expression
  impl.idr:4:5: function application
  impl.idr:4:5: function name
  impl.idr:4:5: name
  impl.idr:4:5: name
  impl.idr:4:5: identifier
  impl.idr:4:5: identifier
```

The diff is a bit cluttered with the rename of `fgetState` & co. to `fget` & co. If that's a problem, I can move that commit to a separate pull request or remove it altogether.

I had to refactor `PParser.hs` a bit, too.

### CODE REVIEW

**Comment by ziman** [comment]
With some [disambiguation of parser descriptions](https://github.com/ziman/idris/compare/parser-trace...ziman:disambiguate-parser-trace?expand=1), the above can be improved as:
```bash
Parser trace:
  impls.idr:1:8: identifier
  impls.idr:1:8: identifier
  impls.idr:3:1: function modifier
  impls.idr:3:1: function modifier
  impls.idr:3:1: function name
  impls.idr:3:1: name
  impls.idr:3:1: simple name
  impls.idr:3:1: identifier
  impls.idr:3:1: identifier
  impls.idr:3:6: type signature
  impls.idr:3:6: dependent type signature
  impls.idr:3:6: static modifier
  impls.idr:3:7: function name
  impls.idr:3:7: name
  impls.idr:3:7: simple name
  impls.idr:3:7: identifier
  impls.idr:3:7: identifier
  impls.idr:3:11: type signature
  impls.idr:3:11: dependent type signature
  impls.idr:3:11: static modifier
  impls.idr:3:11: external or internal expression
  impls.idr:3:11: internal expression
  impls.idr:3:11: function application
  impls.idr:3:11: function name
  impls.idr:3:11: name
  impls.idr:3:11: simple name
  impls.idr:3:11: identifier
  impls.idr:3:11: identifier
  impls.idr:3:19: dependent type signature
  impls.idr:3:19: static modifier
  impls.idr:3:19: external or internal expression
  impls.idr:3:19: internal expression
  impls.idr:3:19: function application
  impls.idr:3:19: function name
  impls.idr:3:19: name
  impls.idr:3:19: simple name
  impls.idr:3:19: identifier
  impls.idr:3:19: identifier
  impls.idr:4:1: function declaration core
  impls.idr:4:1: pattern
  impls.idr:4:1: function clause
  impls.idr:4:1: function name
  impls.idr:4:1: name
  impls.idr:4:1: simple name
  impls.idr:4:1: identifier
  impls.idr:4:1: identifier
  impls.idr:4:6: dependent type signature
  impls.idr:4:6: static modifier
  impls.idr:4:6: external or internal expression
  impls.idr:4:6: internal expression
  impls.idr:4:6: function application
  impls.idr:4:6: function name
  impls.idr:4:6: name
  impls.idr:4:6: simple name
  impls.idr:4:6: identifier
  impls.idr:4:6: identifier
```

What I find interesting is that `identifier` seems to be repeated always twice.

**Comment by david-christiansen** [comment]
This is great! Thanks! I can't wait to get a ":parse" command added to the IDE protocol! I vote that we also merge the disambiguation.

Is there a way to get it to only parse, and not type check, from the command line? That might be nice for non-IDE-mode highlighting tools, e.g. for vim users.

**Comment by david-christiansen** [comment]
What would it take to get it to dump spans instead of absolute locations?

**Comment by ziman** [comment]
Spans would actually be surprisingly easy, now that I think about it. I even think we can do a much better trace, which would also list whether any given call was successful or not. (Unless we can't. I haven't tried yet, maybe there's something lurking in dark corners.)

What would the form of the output of `:parse` be? An AST in S-expressions?

**Comment by ziman** [comment]
Uh, having spans, you could actually recover the hierarchy and the whole AST, I guess. Sounds too intriguing to leave it alone...

**Comment by ziman** [comment]
It seems to be a bit tricky. I'll close this pull request while I work in the branch.

**Pull request closed without merging**
