### PR TITLE
Finds the difference between two Nats

### PR DESCRIPTION
**Pull request by zenntenn**
Total function that finds the difference between two Nats, order independent.	

new file:   libs/contrib/Data/Nat/Difference.idr

### CODE REVIEW

**Comment by david-christiansen** [comment]
Thanks!

This seems like it will be a very small module, when all is said and done. Why not put it in a more general module?

**Comment by zenntenn** [comment]
I couldn't find any appropriate modules in Contrib. Do you have a
suggestion of which one?

**Comment by david-christiansen** [comment]
What about calling it Data.Nat?

**Comment by zenntenn** [comment]
@david-christiansen K, I think I added the module correctly to the pull request, but I'm still pretty new to Github so I might have done something wrong.

**Comment by david-christiansen** [comment]
One more step: it needs to be added to the package file:
https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/contrib.ipkg#L46-L48

thanks!

**Comment by david-christiansen** [comment]
Thanks!

**Pull request merged**
