### PR TITLE
Added a test for bignums

### PR DESCRIPTION
**Pull request by melted**

### CODE REVIEW

**Comment by melted** [comment]
As the bignums are broken and will fail with this test, it should probably not be merged until #2122 is fixed.

**Comment by david-christiansen** [comment]
This passed Travis. Is that expected?

**Comment by melted** [comment]
I was surprised by that, turns out that Travis didn't run this test.  I don't know why.

I'm thinking of dialing it down a bit, I could run it for 500  in the repl with 16g. It would be nice to not require loads of ram to run it in the repl. 

----- Ursprungligt meddelande -----
Från: "David Christiansen" <notifications@github.com>
Skickat: ‎2015-‎04-‎09 17:16
Till: "idris-lang/Idris-dev" <Idris-dev@noreply.github.com>
Kopia: "Niklas Larsson" <metaniklas@gmail.com>
Ämne: Re: [Idris-dev] Added a test for bignums (#2127)

This passed Travis. Is that expected?

**Comment by david-christiansen** [comment]
Did you remember to add it to the cabal file?

**Comment by melted** [comment]
Superseded by #2138

**Pull request closed without merging**
