### PR TITLE
Add docs for IDE protocol

### PR DESCRIPTION
**Pull request by david-christiansen**

### CODE REVIEW

**Comment by david-christiansen** [comment]
Ping @archaeron - is this what you were looking for?

**Comment by archaeron** [comment]
perfect, thanks :+1:
I will expand this if I see something missing

**Comment by david-christiansen** [comment]
Great!

/David (from phone)

**Comment by jfdm** [comment]
Not to be a nag but the placement of this file feels a little off. I understand it refers to implementation details but shouldn't this be put in the 'reference' guide folder and not in a newly created and separate `ide` folder. I envisaged the reference guide to document things like the IDE protocol and other implementation details i.e. grammar and like items.

**Comment by david-christiansen** [comment]
There's a reason I didn't just merge it! This is my first real contribution to the ReST docs. I'll move it.

**Comment by david-christiansen** [comment]
@jfdm As /docs is kinda your domain, I'll wait for your review before a merge (or merge yourself)

**Comment by jfdm** [comment]
The new placement for the documentation is better now.

**Pull request merged**
