### PR TITLE
Added BSD licensed getline and used that to read string from file

### PR DESCRIPTION
**Pull request by ahmadsalim**

### CODE REVIEW

**Comment by ahmadsalim** [comment]
This fixes #2077

**Comment by edwinb** [comment]
Thanks for the fix!

**Comment by ahmadsalim** [comment]
Thanks to Christos Zoulas, who decided to contribute `getline` under a BSD license and make all of our lives easier.

**Comment by Heather** [comment]
@edwinb @ahmadsalim Makefile?

**Comment by ahmadsalim** [comment]
@Heather Oh thanks, I must have missed that :).

**Pull request merged**
