### PR TITLE
Add some propositional logic theorems

### PR DESCRIPTION
**Pull request by nickdrozd**
These aren't useful for anything, but they might be of interest as a reference.

### CODE REVIEW

**Comment by nickdrozd** [comment]
Appveyor failure seems unreleated.

**Comment by jfdm** [comment]
I have not looked at this in detail, however, two things stand immediately out:

1. There is a missing module definition.
2. It would be better if the module's file name matched the style used elsewhere in `libs/`.

Once these are fixed, then we can look at the rest of the code.

**Comment by nickdrozd** [comment]
@jfdm Done

**Comment by melted** [comment]
Thanks for the PR!

**Pull request merged**
