### PR TITLE
Consolidate unique tests

### PR DESCRIPTION
**Pull request by steshaw**
Partially addresses #2577.

### CODE REVIEW

**Comment by zjhmale** [comment]
@steshaw should we make it consecutive? i mean use `unique002` instead of `unique004`.

**Comment by steshaw** [comment]
@zjhmale it was consecutive when I started this patch. There existed `unique001`, `unique002` and `unique003` so I created `unique004`.

There are plenty of other "holes" in the sequencing.

**Comment by zjhmale** [comment]
@steshaw cool.

**Comment by melted** [comment]
Thanks!

**Pull request merged**
