### PR TITLE
Adjustments to logging

### PR DESCRIPTION
**Pull request by jfdm**
+ iLOG has been removed. Everything logged must now have its level explicitly mentioned.
+ Everything that was orginally at logging level 1 that was not reporting where in the building process we were has been shunted down to level 2.
+ Logging level 1 reports:
  + Which file we are looking at.
  + Where in the compilation process we are.
  + Some minor errors that are logged for generating record update functions.

### CODE REVIEW

**Comment by jfdm** [comment]
I am making some more adjustments to the logging to enable reporting that is more gradual in its verbosity.

**Comment by david-christiansen** [comment]
@jfdm is this still in the "hold off merging" state?

**Comment by jfdm** [comment]
I havn't had time to do the other changes I wanted so I am happy for my current changes to logging to be merged. However, it also looks like I have polluted this branch through a rebase and it cannot be automatically merged. Ouch. I shall see what I can do to fix that. then we can merge.

**Comment by david-christiansen** [comment]
OK. Has @edwinb taken a peek at this yet? I think he's the biggest user of the built-in logging.

**Comment by jfdm** [comment]
no he hasn't and I think i have screwed the branch up royally. Am going to abandon and restart this at some point.

**Comment by jfdm** [comment]
There are some other logging capabilities that could be added and will look at adding them in my next attempt.

**Pull request closed without merging**
