### PR TITLE
Feature/package list

### PR DESCRIPTION
**Pull request by NobbZ**
This is a quick and dirty solution for #1071.

I wish I were able to implement output of metadata, but since there is
no metadata saved (currently) alongside of a package, there is nothing
to display.

Displaying metadata in the output of this subcommand would mean that
there have to happen further improvements in the package-system of
idris.

Please see my proposal in #1126.

### CODE REVIEW

**Comment by NobbZ** [comment]
Sorry for failing tests, when I removed stylish-haskell's interference, it appears that I removed an import too much ;) Will provide an update as soon as possible

**Comment by david-christiansen** [comment]
The libdir can contain subdirectories that aren't packages. For example, on my machine it presently contains the CSS files for idrisdoc in a subdirectory.

I think that your function `showPkgs` should check that the directories contain at least one `.ibc` file.

Additionally, it would be convenient if it were split into two functions: one that found the list of packages, and another that displayed it. That way, the IDE helper can easily be extended to provide a list of available packages for things like autocompletion. But I can do this myself when I get that far.

Thanks for the contribution!

**Comment by NobbZ** [comment]
> The libdir can contain subdirectories that aren't packages. For example, on my machine it presently contains the CSS files for idrisdoc in a subdirectory.

Sorry, I wasn't aware of this possibility.

> I think that your function showPkgs should check that the directories contain at least one .ibc file.

I will go and implement this, but how deep do I need to look? Will there always be an `.ibc` in the root-folder of the package, or do I need to look deeper?

> Additionally, it would be convenient if it were split into two functions: one that found the list of packages, and another that displayed it.

Thought about this, but I wasn't sure where to put the function that creates the list of packages, so I put it into the display for now.

**Comment by david-christiansen** [comment]
I believe they can be arbitrarily deep, though @edwinb may have changed that with the index file that he recently added.

Thanks again!

**Comment by edwinb** [comment]
The index file is nothing more than a list of imports to allow :search and :apropos to know where to look, so it won’t affect anything else.

**Comment by bmsherman** [comment]
I am working on a function `installedPackages :: IO [String]` that lists the installed packages (this will be useful for REPL completion as well). Once I get that, then you can just call that function for the command line function.

**Comment by david-christiansen** [comment]
@edwinb My thought was that it would put a `.ibc` in the root of each package, allowing an easy way to tell packages from non-packages without recursively listing the subdirectories' contents.

**Comment by LeifW** [comment]
What kind of metadata would we want for installed packages? Some kind of
version number, date installed, source, ...?

**Comment by NobbZ** [comment]
@bmsherman 
> I am working on a function installedPackages :: IO [String] that lists the installed packages (this will be useful for REPL completion as well). Once I get that, then you can just call that function for the command line function.

So I leave my function as is for now. and wait until yours is finished, then it should be easily possible to use yours instead of my quickhack.

@LeifW
> What kind of metadata would we want for installed packages? Some kind of
version number, date installed, source, ...?

For displaying the packages, I think, version number is the very least thing. Next most interesting fact is installation source. The source would be most valuable if we get better package-management with different kind of sources, like local, git (branch, tag, commit) (or other VCS), some catalogue (like hackage) etc…

**Pull request merged**
