### PR TITLE
update sqlite3 bindings

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by david-christiansen** [comment]
Thanks for updating these!

Is there a reason why you don't use https://github.com/david-christiansen/IdrisSqlite? The reason I'm interested is that I think the one in `contrib/`should probably either be deleted or spun out into a separate repo and I'd like to figure out which option.

**Comment by Heather** [comment]
@david-christiansen it's just recently I was searching for `mkForeign` and discovered that there are something inside repository which is not updated yet so I desired to update it, just in this case.

**Comment by jfdm** [comment]
I have added the IdrisSqlite project to the third-party pages. This should help with discoverability of projects.

**Comment by david-christiansen** [comment]
Thanks, @jfdm. In the meantime, it doesn't hurt to have things in the repo actually work :)

**Pull request merged**
