### PR TITLE
Enum for bits

### PR DESCRIPTION
**Pull request by colin-adams**
I encountered an error message in code that I was writing that there was no Enum implementation for Bits8. It seemed easier to implement this than rewrite the code, so ...

### CODE REVIEW

**Comment by jfdm** [comment]
@colin-adams thanks for the PR, however, it looks like you have included commits from #3126. Is it possible to separate the duplicate commits? Either than, or we can deprecate #3126, and this PR supersedes #3126.

**Comment by ahmadsalim** [comment]
I prefer if the commits were separate, since they concern different areas.

**Comment by colin-adams** [comment]
Oh. I meant to have branched off master. I'll throw this away and start again. Sorry.

**Comment by jfdm** [comment]
Apologies not necessary, been there, done that, have the t-shirt collection. Just push to the same branch and everything can carry on as normal. Time can be rewritten.

**Comment by ahmadsalim** [comment]
Yeah, don't worry. 
Also, I think that @jfdm meant the last part as in git history can be rewritten (and not philosophically).

**Pull request closed without merging**
