### PR TITLE
README: How to run with pruviloj in emacs

### PR DESCRIPTION
**Pull request by kaeluka**
I stumbled over this missing piece of information and thought that others need not have the same problem :-)

### CODE REVIEW

**Comment by kaeluka** [comment]
Meta comment: this is the second trivial PR I'm submitting within 24 hours; I'm planning to submit more documentation fixes as I find problems. I personally think that many trivial PRs are better than few big ones, but let me know if you'd prefer some other way.

**Comment by david-christiansen** [comment]
Lots of small docs PRs are great.

But I'm not so convinced that Emacs mode information belongs here, rather than in the Emacs mode's docs. After all, Idris is a multi-editor language :-)

**Comment by david-christiansen** [comment]
Also, in the Emacs mode, you can get it to make those lines for you with M-x idris-add-idris-load-packages RET , and it'll give you autocomplete of the installed packages.

**Comment by kaeluka** [comment]
I see why you won't make it emacs specific.
*But* I stumbled over this, some hint would've helped me. I'm happy to amend the text I put there (or you can).
Suggestion: instead add a new question in the FAQ instead: "Q: I get error this-and-that in emacs // A: use idris-add-idris-load-packages".

If you don't like that, and don't have a better suggestion: close the PR, I won't mind (really).

**Comment by melted** [comment]
I think it makes sense to have a pointer about this in both emacs mode and pruviloj docs.

**Comment by ahmadsalim** [comment]
@kaeluka I think adding a question to the FAQ about packages seems like a good idea!

I will close the PR since there has not been any activity, and I agree with @david-christiansen that this seems to belong more to the Emacs documentation than here.

**Pull request closed without merging**
