### PR TITLE
Print error message if :exec'ed program exits with failure

### PR DESCRIPTION
**Pull request by yanok**
Check the result code of the compiled program and print an error message if it
didn't return success.

Partially solves #4312.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@yanok Thank you for the PR!

Can you please add a test case and a CHANGELOG entry? 😄

**Comment by yanok** [comment]
@ahmadsalim do you think it is really worth a CHANGELOG entry?

**Comment by ahmadsalim** [comment]
@yanok Sure 👍

**Comment by yanok** [comment]
@ahmadsalim I've updated the PR.

**Comment by ahmadsalim** [comment]
@yanok Thanks! Please, exclude your test from the javascript suite, since it is failing there 😄

**Comment by yanok** [comment]
@ahmadsalim done! but what's the general rule? Tests that rely on :exec should be `C_CG`? Or something else? I wonder how other tests that try to run the compiled results work with the JS backend...

**Comment by ahmadsalim** [comment]
@yanok I think you are relying on the C IO somehow. Maybe @edwinb know more?

**Pull request merged**
