### PR TITLE
Implement a RWS monad for the C backend

### PR DESCRIPTION
**Pull request by melted**
It doesn't really do anything yet, but threading state through the code generation will be useful in the future. For example, better error handling (when we have the source locations in the codegen), various optimizations, or locally decide if some declaration needs to be put on the top level.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@melted Any reason it has not been merged yet?

**Comment by melted** [comment]
Not really, it would be nice to add some functionality that took advantage of the monad. But I'm not going to do that for a while as I got sidetracked by LLVM. So should probably be merged as is.

**Comment by edwinb** [comment]
It turns out, unfortunately, that doing this is a massive performance hit for generating code of any significant size. So unless there is a really convincing benefit for adding the monad I think we're going to have to undo this for now. As evidence, here's the profile summary for compiling Blodwen at the moment:

````
COST CENTRE                   MODULE             %time %alloc

bcc                           IRTS.CodegenC       52.2   64.4
loadInputs.tryLoad            Idris.ModeCommon    23.2   19.4
compare                       Idris.Core.TT        4.4    0.0
==                            Idris.Core.TT        1.6    0.0
getEntry                      Idris.IBC            1.2    1.1
forwardChain.reduceConstraint Idris.Erasure        1.2    0.3
get                           Idris.Core.Binary    1.1    2.0
decodeUtf8With                Data.Text.Encoding   0.6    1.1
get                           Idris.Core.Binary    0.5    1.2
````

And here's what it is if I undo this patch:

````
COST CENTRE                   MODULE             %time %alloc

loadInputs.tryLoad            Idris.ModeCommon    49.9   53.6
compare                       Idris.Core.TT        8.9    0.0
==                            Idris.Core.TT        3.2    0.0
getEntry                      Idris.IBC            2.7    3.2
forwardChain.reduceConstraint Idris.Erasure        2.4    0.9
get                           Idris.Core.Binary    2.4    5.4
runIO                         Idris.AbsSyntax      1.8    0.5
decodeUtf8With                Data.Text.Encoding   1.3    2.9
loadInputs                    Idris.ModeCommon     1.1    1.2
get                           Idris.Core.Binary    1.1    3.3
compare                       Idris.Core.TT        1.1    0.0
buildDepMap.unionMap          Idris.Erasure        1.0    1.7
idrisMain                     Idris.Main           1.0    1.2
buildDepMap.dfs               Idris.Erasure        0.7    1.3
get                           Idris.Core.Binary    0.7    1.2
bcc                           IRTS.CodegenC        0.5    1.5
````

**Comment by melted** [comment]
Yeah, that's bad.

**Pull request merged**
