### PR TITLE
Add section on package creation, and typo fixes.

### PR DESCRIPTION
**Pull request by jfdm**
This commit address #2032, and addes information about package
creation. This content is taken from the Idris website.  Other
typographic fixes for use with reST syntax are fixed.

### CODE REVIEW

**Comment by edwinb** [comment]
Thanks for this - I'll put a link on the web site when it's up. Just one thing before this is merged... "Idris" shouldn't be written as code - it should just be in the normal font. There isn't anything particularly special about a programming language name to make it a different font, it's just a proper noun.

**Comment by jfdm** [comment]
Ah okay. Unfortunately, I have gotten into the habit of writing it in a 'code' font. I will change the rest of the tutorial once I get back to my computer. Should be a simple search and replace job.

**Comment by jfdm** [comment]
This request also now fixes the fortification of Idris in the user documentation to be normal font.

**Comment by jfdm** [comment]
@edwinb Just a bump to say that the new section of the tutorial is public. together with changes to the typos concerning Idris, I took the liberty of merging the changes myself:

    http://idris.readthedocs.org/en/latest/tutorial/packages.html

**Pull request merged**
