### PR TITLE
Prelude.Bits: clarify serialization of BitsX for X={8,16,32,64}

### PR DESCRIPTION
**Pull request by jmitchell**
* Add bXToHexString and bXToBinString
* Deprecate bXToString
* Add documentation
* Add bXToBytes : BitsX -> List Bits8 functions

### CODE REVIEW

**Comment by jmitchell** [comment]
Implements #3675.

**Comment by edwinb** [comment]
Great, thanks! Will merge once the checks are done.

**Comment by jmitchell** [comment]
Interesting, this hits an unsupported case under the node code generator.

```
Error: test/bounded001
/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1417
  i$valstack[i$valstack_base + 1] = (function(){throw new Error("Not implement
                                                      ^
Error: Not implemented: LTrunc (ITFixed IT32) (ITFixed IT8)
    at /home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1417:55
    at _idris_Prelude_46_Bits_46_b32ToBytes (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1417:122)
    at i$RUN (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:1351:10)
    at main (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:2728:3)
    at Object.<anonymous> (/home/travis/build/idris-lang/idris-0.99.1/test/bounded001/bounded001:2730:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
OK (32.85s)
    bignum002:         OK (6.36s)
  Bounded
    bounded001:        FAIL (5.69s)
      --- test/bounded001/output	2017-03-06 01:11:15.453876002 +0000
      +++ test/bounded001/expected	2017-03-06 00:57:18.000000000 +0000
      @@ -1,2 +1,6 @@
       FFFF
       0000
      +FFFFFFFF
      +00000000
      +FFFFFFFFFFFFFFFF
      +0000000000000000
```

**Comment by jmitchell** [comment]
Reproduces locally using `cabal test --test-options="--node --pattern bounded001"`.

**Comment by jmitchell** [comment]
Indeed, some cases aren't handled in the code generator. See around https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/CodegenJavaScript.hs#L760

Should the missing `LTrunc` cases be added? If so, under this PR?

**Comment by edwinb** [comment]
Oh, that's unfortunate. Yes, I suppose we'd better add them! This PR would be as good a place as any, at least if you can easily see how to do it.

**Comment by edwinb** [comment]
Thanks for the fixes!

**Pull request merged**
