### PR TITLE
Add note about Unicode operators to official FAQ

### PR DESCRIPTION
**Pull request by steshaw**
Added the note about Unicode operators from the Unofficial FAQ to the official one.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
I think there was a reason that it was in the unofficial one, but I can't recall what.

**Comment by steshaw** [comment]
@jfdm said something like "pull requests appreciated" on IRC. I simply obliged :). If this does get accepted into the official FAQ, perhaps we should remove it from the unofficial one on the wiki though?

**Comment by ahmadsalim** [comment]
@steshaw I mean if no one minds, then it is fine. Yeah, it would be good to have deduplication between the official and unofficial FAQ

**Comment by jfdm** [comment]
My only concern with this FAQ is the use of first person narration; which was okay in the *Unofficial FAQs*. It *might be* better to keep the same narrative voice used through-out. 

Speaking generally about moving FAQs from unofficial to official. I think we should keep it more at the obvious Questions, and more technical ones in the unofficial FAQs. Otherwise we will need to start categorising the official FAQs.

**Comment by steshaw** [comment]
@jfdm I'll see if I can switch to the narrative voice.

I reckon there should be a QA about type class coherence and probably a separate on on type class resolution. It sounds like this would belong in the Unofficial FAQ or even "Idris for Haskellers" and/or "Idris coming from Scala" (which probably doesn't exist yet).

**Comment by jfdm** [comment]
Ah much better. Sorry for being picky about it, but nice to have the *Official* FAQs being consistent and less of a rag tag bunch of things.

> I reckon there should be a QA about type class coherence and probably a separate on on type class resolution. It sounds like this would belong in the Unofficial FAQ or even "Idris for Haskellers" and/or "Idris coming from Scala" (which probably doesn't exist yet).

PRs/Addition to the wiki are welcome...although remember we have interfaces and not type classes ;-)

As for a "Idris coming from Scala" again PRs welcome. I've often thought about having an *Idris coming from X* series in the docs and migrating things over from the github wiki. But that can wait for another day.

**Comment by steshaw** [comment]
No worries, @jfdm. It's nice to keep the official docs more professional.

If I put something together for the wiki on the common type class questions I'll be sure to mention that they're called interfaces in Idris :).

**Comment by Melvar** [comment]
@steshaw I believe the point of the different name is to signal that they’re not meant to be the same thing as Haskell typeclasses. If you’re willing to indulge this, don’t introduce them as a variation of the same thing, introduce them as a similar thing.

**Comment by steshaw** [comment]
@Melvar Thanks, that's a good approach.

**Pull request merged**
