### PR TITLE
Prove LTE antisymetry and mark LTE related functions total

### PR DESCRIPTION
**Pull request by jachymb**
I have proven antisymetry for LTE. It is important property, because together with reflexivity (`lteRefl`) and transitivity (`lteTransitive`) this proves that (Nat, LTE) is a partially ordered set, hence I believe that `lteAntisymetric` should be at the same place in code as the other two. Further, in maths, it is a common proof technique to prove equality by proving inequality bound in both directions.

Further, I have marked some LTE related functions as total (they are), in order to make the code more consistent with the rest of the file.

### CODE REVIEW

**Comment by xekoukou** [comment]
Hello @jachymb, the file contains the "%default total" in the beginning which means that all functions are total.

Also, eqSucc is defined in a lower position than your function, hence the error.

**Comment by jachymb** [comment]
@xekoukou : Why are most functions in the file marked as `total` explicitly anyway then? Is it for historical reasons?

**Comment by jachymb** [comment]
@xekoukou : Is it better to move `eqSucc` above `lteAntisymetric` or to move `lteAntisymetric` below `eqSucc` accodring to Idris libs coding best practices?

**Comment by xekoukou** [comment]
1. Probably.
2. I do not know, give it a go and probably others will tell what is best.

**Comment by jachymb** [comment]
I have fixed the code to use `cong` instead `eqSucc`

**Comment by justjoheinz** [comment]
Wouldn't it be more consistent with the other proofs to write the signature `total lteAntisymetric : {n : Nat} -> {m : Nat} -> LTE n m -> LTE m n -> n = m`  without the implicit arguments?

**Comment by jachymb** [comment]
@justjoheinz Good point. I have removed the implicit arguments from the signature.

**Comment by anton-trunov** [comment]
There is also no need in bringing `n` and `m` into scope with `{n = ...}` and `{m = ...}`.

**Comment by jachymb** [comment]
@anton-trunov Personally, I find it the most readable as it is now. Is this a required change in order to merge the PR?

**Comment by anton-trunov** [comment]
@jachymb I don't really know if it is required. However, bringing those implicits into scope makes the new code less consistent with the existing code. The existing code in `Prelude.Nat` uses implicits, but as far as I know it does so when it is really needed (like in `lteRefl`).

**Comment by JanBessai** [comment]
Please also take https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Decidable/Order.idr into consideration. It already includes antisymmetry proofs for natutal and finite numbers.

**Comment by jachymb** [comment]
Honestly, I did not know about Decidable.Order.

**Comment by JanBessai** [comment]
It has been living a shadowy live since 2013 #281 . At some point there was an issue to consolidate operations like lte, but I cannot find it anymore.

**Comment by ahmadsalim** [comment]
@jachymb If you could consolidate the `Decidable.Order` properties with this, I think we would happily merge it.

**Comment by jachymb** [comment]
@ahmadsalim I am not sure what is meant by that. :(

**Comment by ahmadsalim** [comment]
@jachymb I meant move the relevant functions from `Decidable.Order` (namely those that don't relate to decidability) to where your PR is and make the style more uniform.

**Comment by ahmadsalim** [comment]
I will close the PR since it seems that there has not been updates for a long time. If you are interested in finishing the PR, please reopen it with the code updates.

Thanks.

**Pull request closed without merging**
