### PR TITLE
Export intermediate representation as JSON

### PR DESCRIPTION
**Pull request by melted**
This adds an option to pass the intermediate representations JSON-encoded to the backend. This makes it possible to build backends in other languages than Haskell.

### CODE REVIEW

**Comment by david-christiansen** [comment]
This is a great idea!

**Comment by jfdm** [comment]
First off, this is a good idea. Kudos.

However, I have some reservations about the implementation concerning its placement w.r.t. codegen targets and how it is plugged into the compiler. Rather than use a boolean flag can we either:

a) express the JSON output as another codegen target i.e. have `idris-codegen-json`; or alternatively 
b) extend `CodeGen` to provide an additional constructor for portable representations.

Of the two I am more in favour of (a), but am also inclined for (b).

**Comment by melted** [comment]
I don't like a) because it would mean that backends using this wouldn't be
as seamless in use as the current backends. Outputting the json is useful,
and I have a backend that do that, but making Idris unable to run the whole
compilation process would require backends that use this to supply their
own scripts to run it all through. Also it would mean packaging another
huge executable. They compress well, but it feels silly to have a 30 meg
program that does something trivial.

**Comment by melted** [comment]
Well, that's the most absurd Travis failure I've seen.

**Comment by melted** [comment]
I can change the switch to something that parallels `--codegen` and make a new Codegen constructor.

**Comment by jfdm** [comment]
I understand your reservations about a separate JSON codegen executable, but I do not share them. 

However, the second option of extending `CodeGen` might be the best way forward, you may want to parameterise the constructor such that in the event we want to change the format or support multiple formats (e.g. XML or Sexp) this can be achieved more easily.

Alternatively, extending `OutputType`, might be a third option to consider, however this again ties generation of the portable output to the code generator itself rather than in the 'compiler'.

**Comment by melted** [comment]
Thanks for the comments.  It looks cleaner now. Documentation will follow.

**Comment by jfdm** [comment]
TBH, it would have been nicer to review the secondary changes made, prior to merging into master. Primarily to show that there was a review of said changes, and also consensus about the changes. Maybe this is something to take into account for future PRs.

**Pull request merged**
