### PR TITLE
Replace _ patterns with fresh variables under @-patterns

### LINKED ISSUE #1806: Underscore patterns broken in at-patterns
Underscore patterns seem to fail in at-patterns.

```
data Foo = MkFoo Int

broken : Foo -> ()
broken p@(MkFoo _) = ()
```

Fails with:

```
$ idris --version
0.9.15.1-git:d40cd6f
$ idris --check /tmp/a.idr 
/tmp/a.idr:4:8:Incomplete term let p = MkFoo ([__]) in ()
$ 
```

### PR DESCRIPTION
**Pull request by david-christiansen**
Also, add test.

Fixes #1806.

### CODE REVIEW

**Comment by david-christiansen** [comment]
@edwinb I don't want to merge this myself because it adds use of Uniplate to replace a 90 line function with a 3 line function. If you don't want that in the code base, I understand.

**Comment by david-christiansen** [comment]
@edwinb on IRC it sounded like you were OK with this - am I interpreting correctly?

Thanks!

**Comment by edwinb** [comment]
Sure, seems fine to me.

**Comment by david-christiansen** [comment]
Thanks!

**Pull request merged**
