### PR TITLE
Nothing - just checking master

### PR DESCRIPTION
**Pull request by steshaw**
Just wanted to provoke a CI build of master.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@steshaw Please do not submit PRs just to provoke new Travis builds. If you want to rerun a build, please ping/contact one of the maintainers and tell them to do it.

**Comment by ahmadsalim** [comment]
@steshaw You can also setup Travis for your own fork, by logging in at https://travis-ci.org/.

**Comment by steshaw** [comment]
Sorry to have been a bother, @ahmadsalim. I didn't know any other way to do it and no-one seemed to be around on IRC. It wasn't exactly EU time. Anyhow, the compile error building `contrib` doesn't seem to be happening on Travis.

**Comment by ahmadsalim** [comment]
@steshaw It is fine :), but just for next time to avoid cluttering the issue tracker with empty PR issues.

**Comment by steshaw** [comment]
No worries, @ahmadsalim. Looks like I've got my own Travis all set up for [steshaw/idris](https://github.com/steshaw/idris). Thanks!

**Pull request closed without merging**
