### PR TITLE
Enable GHC warnings [WIP]

### PR DESCRIPTION
**Pull request by steshaw**
I've enabled `-Wall` and `-fwarn-tabs`.
- Configured for all libraries, executables and test-suites.
- Warnings are turned into errors using -Werror by the CI flag.

Once complete, this patch will address #3229

### CODE REVIEW

**Comment by steshaw** [comment]
At this point the AppVeyor build should be failing too. It must be that it isn't using the `CI` flag. I'll turn it on.

**Comment by steshaw** [comment]
There we go, such an improvement to have a failing build ;)

**Comment by melted** [comment]
I don't think this is viable. It warns about perfectly legal and fine Haskell, like it bails out now at "top-level binding without signature". That's a programming style issue.

**Comment by steshaw** [comment]
@melted, I think it may be better to discuss this issue at #3229. However, to quickly address your issue, it would be possible to disable that specific warning (with `-fno-warn-missing-signatures`).

**Comment by ahmadsalim** [comment]
I think it would be preferable to enable specific warnings we find useful than use `-Wall`.

**Comment by steshaw** [comment]
@ahmadsalim that would be reasonable. Another way to go would be to use  `-Wall` on a file by file basis. If one day all files are `-Wall` clean then the flag could be moved to the cabal file. Closing this for now. Closing this for now. Any further discussion could happen at #3229.

**Pull request closed without merging**
