### PR TITLE
Added static analysis to C RTS

### PR DESCRIPTION
**Pull request by ahmadsalim**
Added `cppcheck` to run on the C Idris RTS folder.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
One could also investigate adding http://www.coverity.com, which is free for open-source projects.
This however requires someone with commit rights.

**Comment by puffnfresh** [comment]
cppcheck looks like it gave some useful analysis already. Nice! :+1:

**Comment by jfdm** [comment]
Ah yes, use of Coverity Scan would be nice as well. I have been meaning to look at integrating some static analysis of the rtses.  I will look into it during my hackthon time.

**Comment by mattias-lundell** [comment]
I tried coverity for Idris rts a month ago https://scan.coverity.com/projects/4009. However it seems that only members of the project can view results.

**Comment by jfdm** [comment]
The reason being is [responsible disclosure](https://scan.coverity.com/faq#who-can-have-access), which I am all in favour for. I am all in favour of using coverity scan but the final decision should lie with those who have commit rights, as they will see the increase in mail.

**Pull request merged**
