### PR TITLE
Data.Graph & Data.Polyhedra

### PR DESCRIPTION
**Pull request by markfarrell**
Add Data.Graph & Data.Polyhedra:

* Value-Dependent Graph and Polyhedra data types, inspired by PureScript Graphs.
* No operations or typeclass instances for them yet. Suggestions?

Data.Graph:

```idris
module Data.Graph

import Data.Vect

data Edge e = MkEdge e e

data Graph : Nat −> Nat −> Type −> Type −> Type where
  MkGraph : Vect m v −> Vect n (Edge k) −> Graph m n v k
```

Data.Polyhedra:

```idris
module Data.Polyhedra

import Data.Vect
import Data.Graph

data Face f = MkFace (Vect n f)

data Polyhedron : Nat -> Nat -> Nat -> Type -> Type where
  MkPolyhedron : Vect k v -> Vect m (Edge v) -> Vect n (Face v) -> Polyhedron k m n v
```

Signed-off-by: Mark Farrell <m4farrel@uwaterloo.ca>

### CODE REVIEW

**Comment by LeifW** [comment]
Graphs support sum and product, don't they? Maybe Monoid and... whatever else gives "product", might make sense.

**Comment by david-christiansen** [comment]
I'd like to wait to import these until we figure out #2007. I don't know that these are good candidates for `base`, but they would fit in well to `contrib`. We could move them to `base` once there's some operations on them as well as some experience using them in real code.

**Comment by markfarrell** [comment]
Sure, that makes sense.

**Comment by david-christiansen** [comment]
#2007 is merged now - would you mind retargeting this PR so that the new modules go into `contrib` until we get more experience using them and more operations on them?

**Comment by markfarrell** [comment]
Sure, I'll try to get around to it this weekend.

**Comment by david-christiansen** [comment]
Thanks!

**Comment by markfarrell** [comment]
Moved to ```contrib``` now.

**Comment by markfarrell** [comment]
Cool, thanks.

**Pull request merged**
