### PR TITLE
Removed equality from primNames, as it shouldn't be handle specially when adding implicits (the only current use).

### LINKED ISSUE #1419: (=) has inconsistent plicity somehow.
```
Idris> :t (=)
(=) : A -> B -> Type
Idris> \A,B => the (A -> B -> Type) (=)
(input):1:13:When elaborating argument x to function Prelude.Basics.the:
        Can't unify
                (A : Type) -> (B : Type) -> A -> B -> Type
        with
                A -> B -> Type
        
        Specifically:
                Can't unify
                        Type
                with
                        A
Idris> the ((A : Type) -> (B : Type) -> A -> B -> Type) (=)
(=) : (A : Type) -> (B : Type) -> A -> B -> Type
```

### PR DESCRIPTION
**Pull request by ahmadsalim**
Fixes #1419.

### CODE REVIEW

**Comment by Melvar** [comment]
Is there some reason why you don’t run at least one set of tests locally?

**Comment by ahmadsalim** [comment]
Melvar: I have an issue with installing the FFI and it somehow stops in the middle when there are none.

**Comment by Melvar** [comment]
Ah, okay. That is a reason indeed.

**Comment by ahmadsalim** [comment]
Hopefully, everything should be OK now. I have squashed the commits to avoid a long history.

**Comment by david-christiansen** [comment]
Great!

**Pull request merged**
