### PR TITLE
Updated Logging Effect.

### PR DESCRIPTION
**Pull request by jfdm**
+ Fixed namespace of default logger so default is called from module `Effect.Logging`
+ Reworked implementation of default logger to use a record as the
  underlying resource, and added new methods to initialise and
  change the logging levels and logging categories.
+ Simple logger also has method to adjust logging levels.

### CODE REVIEW

**Comment by jfdm** [comment]
Ah, I see the error, I forgot to return the result of the effectful function, will fix.

**Comment by jfdm** [comment]
Right, as far as I am aware I am happy for the effectual logger improvements to be merged now. If someone could do a numpty check then please do so.

**Comment by Melvar** [comment]
It would be nice if you could make your `Show` instance parenthesize properly by defining `showPrec`.

**Comment by Melvar** [comment]
Weird that this doesn’t compile in Travis … I assume it works locally, since it also did for me.

**Comment by jfdm** [comment]
@Melvar, this doesn't work locally for me anymore. It once did, but I think a recent change to how instances work may have changed behaviour. I honestly do not know...it would be nice to have this in the upcoming release.

**Pull request merged**
