### PR TITLE
Enable unified diff for tasty tests

### PR DESCRIPTION
**Pull request by steshaw**
This is a fix for #3309.

This is likely to be a bit of a WIP. Let's see how this plays out on Windows/MSYS2.

### CODE REVIEW

**Comment by steshaw** [comment]
Okay, 4 test failures on Windows/MSYS2.

The other 2 test failures look related to encoding: `basic013` and `primitives001`.

2 failures are related to filenames: `interactive007` and `quasiquote001`. I was wrong about how easy filenames were going to be to identify... May have to normalise the `expected` file as well as the `actual` file (as was done previously). I'll persevere a little while before I give up though as you do get better diffs when things go wrong when you don't hack your `expected` files.

Also, many stray and repeated messages such as:

```
stty: 'standard input': Inappropriate ioctl for device
```

**Comment by steshaw** [comment]
Either Travis or GitHub seems to have gotten themselves into twist. I've tested the `tasty-diff` branch on Mac and Linux without a hitch. I'll try opening another pull-request based on branch `tasty-diff-2`.

**Comment by steshaw** [comment]
\o/

Looks good to merge, @jfdm.

**Comment by melted** [comment]
Hmmm, guess this got there first, so I'll have adapt the stderr patch.

**Comment by steshaw** [comment]
Thanks for merging, @melted! Hope I didn't cause many conflicts in your other patch.

**Pull request merged**
