### PR TITLE
Not silently accepting invalid options in package files

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by gallais** [comment]
re #4255

**Comment by ahmadsalim** [comment]
@gallais I am unsure why this fails. The steps you have followed seem correct, I will take a look next week when I have more time.
Do you potentially know if the output is written to `stderr` instead of `stdout`?

**Comment by gallais** [comment]
Re-attempting this one now that I have managed to get at least
one test case to work on the other PR.

**Comment by ahmadsalim** [comment]
Thank you! @gallais 😄

**Pull request merged**
