### PR TITLE
Remove escapes from expected output in pkg004

### PR DESCRIPTION
**Pull request by melted**
grumble

### CODE REVIEW

**Comment by Melvar** [comment]
This appears to have removed the escapes from the expected output, while changing the call to idris so that the escapes are actually written, so that the result is still the two being inconsistent.

**Comment by melted** [comment]
Yhe other options do nothing when Idris is in pkg mode. So they didn't do anything, it is the ones in the ipkg file that matters. Even better, idris doesn't output ANSI codes when stdout isn't a tty these days, so the --nocolour option isn't necessary anymore.

**Comment by Melvar** [comment]
Something about that statement is incorrect, since on my system this test fails on Idris HEAD, with the difference being precisely color.

**Comment by melted** [comment]
What OS do you have? Travis is happy with this.

The tty check is implemented at https://github.com/idris-lang/Idris-dev/blob/master/src/Util/System.hs#L63 and is used at https://github.com/idris-lang/Idris-dev/blob/9e8930d494325ff68d0aea0aacb01271b81187b0/src/Idris/REPL.hs#L1699

**Comment by melted** [comment]
Ah, of course. That's useless because the package functionality doesn't come via idrisMain. I'll make a fix of some sort.

**Comment by Melvar** [comment]
I’m on Linux and build with I think all the options.

**Comment by melted** [comment]
The escapes comes from trifectas error messages which are pretty-printed. So make them plain to standardize it, as it is outside the options we have to control printing. https://github.com/idris-lang/Idris-dev/pull/2917

**Pull request merged**
