### PR TITLE
Add doc comment and deprecation warning for Float

### PR DESCRIPTION
**Pull request by enolan**

### CODE REVIEW

**Comment by jfdm** [comment]
Looks like some test output needs updating. Also there appears to be a lot of deprecation warnings being generated. Is that because `Float` is used, or because the type synonym is being evaluated and deprecate warning on the use of Double...

**Comment by enolan** [comment]
Oh durr, I should've ran the testsuite. Assume doc only changes couldn't possibly break anything, but of course the deprecation does. I'll look at this tomorrow.

**Comment by enolan** [comment]
Works now :)

**Comment by david-christiansen** [comment]
Thanks for doing this! I'll update the reflection bits.

**Pull request merged**
