### PR TITLE
Silence intero about non-exhaustive patterns in main/Main.hs

### PR DESCRIPTION
**Pull request by steshaw**
- At this point, the list, `fs`, is always non-empty.

### CODE REVIEW

**Comment by melted** [comment]
Why not just match the missing case and call `ifail`? headNote sidesteps our ordinary error reporting. And dragging in another dependency for this seems a high price.

**Comment by steshaw** [comment]
Perhaps that would be better.

However, `safe` is used in Idris the library. I was merely exposing it for use in the `idris` executable. Given that, do you still see it as a high price?

**Comment by melted** [comment]
Ok, the import's ok then. I would still prefer a pattern match on empty or `otherwise` and ifail. headNote may be a better head, but it's still partial, will terminate the program, and not at all something we need to use.

**Comment by steshaw** [comment]
No worries, as I said, it would be better.

Perhaps we should nuke `safe` as AFAICT, there's only one other usage?

**Pull request merged**
