### PR TITLE
Small fix for #4282 and #4299

### PR DESCRIPTION
**Pull request by yanok**

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@yanok Thanks for the PR. Can you please explicate a bit more the reasoning behind your fix?

**Comment by yanok** [comment]
@ahmadsalim Well, I have to admit it was the first time I looked at the Idris internals, so I might be missing something. But my reasoning was along these lines:

The only thing changed is the
```haskell
checkRec (TType _) (TType _) = return False
```
case, which I changed from `False` to `True`.

1. Why returning `False` is a bad idea? I tried to explain this in the commit message, but I'll try to re-state it here. In case of constructor application `checkRec` works by recursively checking all the arguments. Now imagine a constructor applied (among other things) to `Type`. This clause for `TType` would result in the whole application reported as unrecoverable, even if all the other arguments are recoverable. For example, in #4282 `checkRec` gets called with `(=) Type Type (f x) (f y)` and `(=) Type Type (f x) (f x)`. Here pairs `f x` , `f x` and `f y` , `f x` are (correctly) reported as recoverable but because of the `Type`s the whole application is reported as not recoverable.
2. Why it's ok to always return `True`? Well, first of all, I think it's much better to fail to recognise valid impossible pattern, then to accept the invalid one. Then, `checkRec` is only called if there were an unification error. Correct me if I'm wrong, but I think problems with `Type`s are reported as universe errors, not unification errors so in `checkRec` it's safe to assume that two matching `TType`s agree with each other.

**Comment by ahmadsalim** [comment]
@yanok Thanks for the explanation, it sounds reasonable

**Comment by ahmadsalim** [comment]
@edwinb I have merged this, but if something goes wrong please tell me so that I can revert it.

**Comment by edwinb** [comment]
Seems a reasonable fix to me. Thanks!

(I did the now usual thing of checking if the same problem exists in Blodwen - fortunately not! Its approach to type checking makes this rule much simpler to implement because the notion of "recoverable error" just results in holes rather than an error message we have to decode)

**Pull request merged**
