### PR TITLE
add TT to CodegenInfo

### PR DESCRIPTION
**Pull request by joe9**
Hello,

It seems to be a good idea to add the TT to the CodegenInfo, if the backend generators need to check the original representation.

Thanks

### CODE REVIEW

**Comment by melted** [comment]
Looks good! It would be nice to have a type alias for (Def, RigCount, Injectivity, Accessibility, Totality, MetaInformation), it's rather unwieldy.

**Comment by melted** [comment]
Mailing list thread: https://groups.google.com/forum/#!topic/idris-lang/nkFILurqWFI

**Comment by david-christiansen** [comment]
This will also enable a backend that made a nice rendered version of the TT version of a program, which might be nice for learning about the elaborator. Great idea!

**Comment by timjs** [comment]
This is very helpful! However, I think it doesn't export the used parameters of a `TyDecl` as is extracted [here](https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/Compiler.hs#L347) does it?

For example, when generating code for a simple [HelloWorld](https://github.com/timjs/idris-clean/blob/master/Tests/HelloWorld.idr), the constructor of `Prelude.Applicative.Applicative` compiles down to an `LConstructor` with [arity 0](https://gist.github.com/timjs/863dd2295fb5bb0e3203e75c3e8688aa#file-helloworld-icl-L934) instead of the [original 4](https://gist.github.com/timjs/863dd2295fb5bb0e3203e75c3e8688aa#file-helloworld-icl-L5760)!

**Comment by jfdm** [comment]
Just a reminder that any documentation for this backend should also be updated to reflect the changes, and if there is no documentation then it might be a good idea to add something to the docs.

**Comment by joe9** [comment]
@timjs  @melted @david-christiansen 

All this does is add the TT to CodegenInfo. This information has been available to the backend, if it reads the IState. The only big help from this pull request is that the .json file created when using the writePortable has TT now. This would make it easier to format or read with the json tools as there is quite a bit of information there. 

Below is the code snippet to get to the type information, etc, from the backend.

```
c_main :: Opts -> Idris ()
c_main opts = do -- runIO setupBundledCC
                 elabPrims
                 runIO $ putStrLn "before loadInputs"
                 scds <- allSourceDirs
                 runIO $ putStrLn $ show scds
                 loadInputs (inputs opts) Nothing
                 showContext
                 runIO $ putStrLn "before elabMain"
                 mainProg <- elabMain
                 runIO (putStrLn (show mainProg))
                 runIO $ putStrLn "before compile"
                 ir <- compile (Via IBCFormat "9frontc") (output opts) (Just mainProg)
                 runIO $ codegen9FrontC ir
                 runIO (withFile "idris-ir.json" WriteMode (flip writePortable ir))

showContext :: Idris ()
showContext
    = do i <- getIState
         runIO (putStrLn $ "showInterfaces begin ------------------------------------")
         runIO (putStrLn $ show (idris_interfaces i))
         runIO (putStrLn $ "showInterfaces end  -------------------------------------")
         runIO (putStrLn $ "showRecords begin ------------------------------------")
         runIO (putStrLn $ show (idris_records i))
         runIO (putStrLn $ "showRecords end  -------------------------------------")
         runIO (putStrLn $ "showDsls begin ------------------------------------")
         runIO (putStrLn $ show (idris_dsls i))
         runIO (putStrLn $ "showDsls end  -------------------------------------")
         runIO (putStrLn $ "showDataTypes begin ------------------------------------")
         runIO (putStrLn $ show (idris_datatypes i))
         runIO (putStrLn $ "showDataTypes end  -------------------------------------")
         runIO (putStrLn $ "showCallGraph begin ------------------------------------")
         runIO (putStrLn $ show (idris_callgraph i))
         runIO (putStrLn $ "showCallGraph end  -------------------------------------")
         runIO (putStrLn $ "showTyinfodata begin ------------------------------------")
         runIO (putStrLn $ show (idris_tyinfodata i))
         runIO (putStrLn $ "showTyinfodata end  -------------------------------------")
         runIO (putStrLn $ "showFninfo begin ------------------------------------")
         runIO (putStrLn $ show (idris_fninfo i))
         runIO (putStrLn $ "showFninfo end  -------------------------------------")
         runIO (putStrLn $ "showName begin ------------------------------------")
         runIO (putStrLn $ show (idris_name i))
         runIO (putStrLn $ "showName end  -------------------------------------")
         return ()
```

I think it is inevitable to read the idris_records, and idris_datatypes (also, idris_fninfo?) of the IState to get to the type definitions.

This is from https://github.com/joe9/idris-9front-backend/blob/master/src/Main.hs#L36

**Comment by jfdm** [comment]
Can a line be added to the CHANGELOG please to detail the change?

**Comment by joe9** [comment]
The CHANGELOG seems to be for high level stuff. This is vey low level Info. I am not sure what I would add it as. imho, it does not warrant an entry in the CHANGELOG as it does not affect the current working. It is more of a debugging aid.

**Comment by ahmadsalim** [comment]
@joe9 I don't think it would hurt to add a line to `CHANGELOG`, perhaps under miscellaneous updates?

**Pull request merged**
