### PR TITLE
Fix encoding issue on Windows corresponded with `fopen`, `popen` and `argv`.

### PR DESCRIPTION
**Pull request by be5invis**

### CODE REVIEW

**Comment by be5invis** [comment]
cc. @melted

**Comment by melted** [comment]
Thanks!

**Comment by jfdm** [comment]
Can a comment be added to the CHANGELOG detailing this fix. 

Changess/fixes in encoding support on any platform, should be documented.

**Comment by be5invis** [comment]
@jfdm 
Changes are:

* RTS function `fileOpen` and `do_popen` now can handle non-ASCII characters in its arguments.
* `argv` are now correctly encoded in UTF-8 on Windows.

**Pull request merged**
