### PR TITLE
Js IORef support

### PR DESCRIPTION
**Pull request by rbarreiro**
In sequence of #4082, added js support for IORef

### CODE REVIEW

**Comment by ahmadsalim** [comment]
@rbarreiro Thanks for the PR!

Could you please update the CHANGELOG and perhaps add a test using `HasReference`?

**Comment by rbarreiro** [comment]
@ahmadsalim  sure, but what do you mean add a test using HasReference? I was thinking that one test with node backend would be nice, but I am not sure I understand what you mean.

**Comment by ahmadsalim** [comment]
@rbarreiro Maybe just something that tries to use `modifyIORef`.

**Comment by ahmadsalim** [comment]
@rbarreiro In JavaScript and C IOs.

**Comment by ahmadsalim** [comment]
Sorry, `modifyIORef'`.

**Comment by ahmadsalim** [comment]
@rbarreiro Thanks again for the work! 👍

**Pull request merged**
