### PR TITLE
Document interactive theorem proving as deprecated.

### PR DESCRIPTION
**Pull request by jeremy-w**
Puts "DEPRECATED:" in the chapter title and also adds a warning paragraph
at the start of the tutorial chapter.

### CODE REVIEW

**Comment by david-christiansen** [comment]
I think that, perhaps, we should refer them to the section on `Elab` reflection, and not just to the `rewrite` keyword. That will be the eventual replacement for the old-style tactic language. It's almost ready too - I just need to finish implementing `induction` and it will have all the features.

**Comment by david-christiansen** [comment]
@edwinb What do you think about this declaration of deprecation?

**Comment by jeremy-w** [comment]
@david-christiansen I'm trying to rewrite it as you requested, but for some reason, Sphinx doesn't seem to like a cross-reference in a content block. It's showing the literal `ref:foo` in the admonition content block; the same markup in the body text works fine and substitutes in the "Elaborator Reflection" section title with a link there as expected. :\

**Comment by jeremy-w** [comment]
@david-christiansen Got it! The issue turned out to be that the bold markers `**` were somehow preventing the markup from being handled correctly. Yay edge cases. New commits incoming.

**Comment by david-christiansen** [comment]
Thanks for this! I do want to make sure that @edwinb is on board with this change in advertising before we merge it, though.

**Comment by edwinb** [comment]
I think this is a good idea to make clear. For various reasons I don't want to remove tactics for a while (mostly that there's quite a bit of research going on that uses them...) but it's better if we encourage people to use the elaborator reflection in the end.

**Comment by david-christiansen** [comment]
@edwinb Didn't you say on IRC that you'd prefer to mark them as deprecated for the release after the upcoming one? If that's the case, then we should probably merge this one immediately after the release.

**Pull request merged**
